// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// 1-Wire slave: reset/presence detect, write slots (rx), read slots (tx)
// Timing in units of US (clk cycles per microsecond); LSB-first bytes.
// OpenCores onewire slave style.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module _1_Wire_top #(
  parameter int US = 10               // sim: 100ns per us unit
)(
  input  logic       clk,
  input  logic       rst_n,
  inout  tri         dq,
  input  logic [7:0] tx_byte,         // byte sent on read slots (after cmd)
  output logic [7:0] rx_byte,         // last command/data byte received
  output logic       rx_valid,
  output logic       busy,
  output logic       irq
);
  logic dq_s, dq_d;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin dq_s <= 1'b1; dq_d <= 1'b1; end
    else begin dq_s <= dq; dq_d <= dq_s; end
  end
  wire dq_fall = dq_d & ~dq_s;
  wire dq_rise = ~dq_d & dq_s;

  typedef enum logic [2:0] {
    ST_IDLE, ST_RESET_CNT, ST_RESET_REL, ST_PRESENCE,
    ST_WAIT_SLOT, ST_W_SAMPLE, ST_R_DRIVE, ST_TX_BYTE
  } st_t;
  st_t        state;
  logic [15:0] timer;
  logic [2:0]  bit_cnt;
  logic [7:0]  rx_shift, tx_shift;

  assign dq     = (state == ST_PRESENCE || (state == ST_R_DRIVE && !tx_shift[0]))
                  ? 1'b0 : 1'bz;
  assign busy   = (state != ST_IDLE);
  assign irq    = rx_valid;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= ST_IDLE; timer <= '0; bit_cnt <= '0;
      rx_shift <= '0; rx_byte <= '0; rx_valid <= 1'b0;
      tx_shift <= '0;
    end else begin
      rx_valid <= 1'b0;
      case (state)
        ST_IDLE: if (!dq_s) begin
          state <= ST_RESET_CNT; timer <= '0;
        end
        // master reset pulse: low for > ~480us
        ST_RESET_CNT: begin
          if (dq_s) begin
            state <= ST_IDLE;                    // glitch: back to idle
          end else if (timer > 16'd480*US) begin
            state <= ST_RESET_REL;
          end else timer <= timer + 1'b1;
        end
        ST_RESET_REL: if (dq_s) begin
          state <= ST_PRESENCE; timer <= '0;     // bus released: answer
        end
        ST_PRESENCE: begin
          if (timer > 16'd120*US) begin
            state <= ST_WAIT_SLOT; bit_cnt <= '0;
          end else timer <= timer + 1'b1;
        end
        // write slot: master pulls low; sample at ~15us (0=held, 1=released)
        ST_WAIT_SLOT: if (dq_fall) begin
          state <= ST_W_SAMPLE; timer <= '0;
        end
        ST_W_SAMPLE: begin
          if (timer == 16'd15*US) begin
            rx_shift <= {dq_s, rx_shift[7:1]};   // LSB-first assembly
            if (bit_cnt == 3'd7) begin
              rx_byte  <= {dq_s, rx_shift[7:1]};
              rx_valid <= 1'b1;
              bit_cnt  <= '0;
              tx_shift <= tx_byte;               // arm read phase
              state    <= ST_TX_BYTE;
            end else begin
              bit_cnt <= bit_cnt + 1'b1;
              state   <= ST_WAIT_SLOT;
            end
          end else timer <= timer + 1'b1;
        end
        // read slot: master pulls low >=1us then releases; slave holds 0 for bit 0
        ST_TX_BYTE: if (dq_fall) begin
          state <= ST_R_DRIVE; timer <= '0;
        end
        ST_R_DRIVE: begin
          if (timer > 16'd40*US) begin
            if (bit_cnt == 3'd7) begin
              bit_cnt <= '0;
              state   <= ST_WAIT_SLOT;           // done: expect next command
            end else begin
              tx_shift <= {1'b0, tx_shift[7:1]}; // next bit (LSB-first)
              bit_cnt  <= bit_cnt + 1'b1;
              state    <= ST_TX_BYTE;
            end
          end else timer <= timer + 1'b1;
        end
        default: state <= ST_IDLE;
      endcase
    end
  end

endmodule
