// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// LTI simplified: translation flit channel.
// Req flit 44b: {addr[31:0], txnID[11:0], opcode[7:0]... simplified:
//   [43:32]=txnID [31:0]=addr
// Rsp flit 34b: {[33:29]=opcode(5'b00001=OK) [28:17]=txnID [16:1]=data16
//               [0]=respValidTag}
// Credit-based flow control both directions. OpenCores chi / AMBA CHI spec
// (Issue A/B) simplified style.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module ARM_Local_Translation_Interface_top #(
  parameter int CRD_MAX  = 8,
  parameter int RSP_LAT  = 4
)(
  input  logic        clk,
  input  logic        rst_n,
  // request channel (from master into us)
  input  logic [43:0] txreqflit,
  input  logic        txreqflitv,
  output logic        txreqlcrdv,
  // response channel (from us to master)
  output logic [33:0] rxrspflit,
  output logic        rxrspflitv,
  input  logic        rxrsplcrdv,
  output logic        busy,
  output logic        irq
);
  // credits we grant to master (acceptance capacity)
  logic [3:0] rx_crd;
  // credits master grants us (for our responses)
  logic [3:0] tx_crd;
  logic [3:0] crd_timer;

  typedef enum logic [1:0] {C_IDLE, C_LAT, C_SEND} c_t;
  c_t         cstate;
  logic [43:0] req_q;
  logic [3:0]  lat_cnt;

  assign txreqlcrdv  = (crd_timer == 4'd0);
  assign rxrspflitv  = (cstate == C_SEND) && (tx_crd != 0);
  assign rxrspflit   = {5'b00001, req_q[43:32], req_q[15:0], 1'b1};
  assign busy        = (cstate != C_IDLE);
  assign irq         = (cstate == C_SEND) && (tx_crd != 0);

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rx_crd <= CRD_MAX[3:0]; tx_crd <= '0; crd_timer <= '0;
      cstate <= C_IDLE; req_q <= '0; lat_cnt <= '0;
    end else begin
      // credit return to master (acceptance credit replenishment)
      if (txreqlcrdv) begin
        if (rx_crd < CRD_MAX[3:0]) rx_crd <= rx_crd + 1'b1;
        crd_timer <= 4'd7;
      end else crd_timer <= crd_timer - 1'b1;

      // master grants us response credit
      if (rxrsplcrdv && tx_crd < CRD_MAX[3:0]) tx_crd <= tx_crd + 1'b1;

      case (cstate)
        C_IDLE: if (txreqflitv && rx_crd != 0) begin
          req_q  <= txreqflit;
          rx_crd <= rx_crd - 1'b1;
          cstate <= C_LAT; lat_cnt <= RSP_LAT[3:0];
        end
        C_LAT: if (lat_cnt == 0) cstate <= C_SEND;
        else lat_cnt <= lat_cnt - 1'b1;
        C_SEND: if (tx_crd != 0) begin
          tx_crd <= tx_crd - 1'b1;
          cstate <= C_IDLE;
        end
        default: cstate <= C_IDLE;
      endcase
    end
  end

endmodule
