// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// SWD simplified start+32b+parity frame.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module ARM_Serial_Wire_Debug_top #(
  parameter int CLK_FREQ = 50_000_000,
  parameter int BAUD     = 115_200
)(
  input  logic       clk,
  input  logic       rst_n,
  input  logic       rxd,
  output logic       txd,
  input  logic [7:0] tx_data,
  input  logic       tx_valid,
  output logic       tx_ready,
  output logic [7:0] rx_data,
  output logic       rx_valid,
  output logic       irq
);
  localparam int DIV16 = (CLK_FREQ / BAUD) / 16;

  // ---------------- 16x baud tick ----------------
  logic [15:0] div_cnt;
  logic        tick16;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      div_cnt <= '0;
      tick16  <= 1'b0;
    end else if (div_cnt == DIV16-1) begin
      div_cnt <= '0;
      tick16  <= 1'b1;
    end else begin
      div_cnt <= div_cnt + 1'b1;
      tick16  <= 1'b0;
    end
  end

  // ---------------- TX: 8N1 ----------------
  typedef enum logic [1:0] {TX_IDLE, TX_START, TX_DATA, TX_STOP} tx_t;
  tx_t        tstate;
  logic [3:0] tsub, tbit;
  logic [7:0] tshift;

  assign tx_ready = (tstate == TX_IDLE);

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      tstate <= TX_IDLE; txd <= 1'b1;
      tsub <= '0; tbit <= '0; tshift <= '0;
    end else case (tstate)
      TX_IDLE: if (tx_valid) begin
        tshift <= tx_data; tstate <= TX_START;
        txd <= 1'b0; tsub <= '0;
      end
      TX_START: if (tick16) begin
        if (tsub == 4'd15) begin
          tsub <= '0; tbit <= '0;
          txd <= tshift[0];
          tshift <= {1'b0, tshift[7:1]};
          tstate <= TX_DATA;
        end else tsub <= tsub + 1'b1;
      end
      TX_DATA: if (tick16) begin
        if (tsub == 4'd15) begin
          tsub <= '0;
          if (tbit == 4'd7) begin
            txd <= 1'b1;
            tstate <= TX_STOP;
          end else begin
            tbit <= tbit + 1'b1;
            txd <= tshift[0];
            tshift <= {1'b0, tshift[7:1]};
          end
        end else tsub <= tsub + 1'b1;
      end
      TX_STOP: if (tick16) begin
        if (tsub == 4'd15) begin
          tsub <= '0;
          tstate <= TX_IDLE;
        end else tsub <= tsub + 1'b1;
      end
      default: tstate <= TX_IDLE;
    endcase
  end

  // ---------------- RX: 8N1, 16x oversample ----------------
  logic rxd_s, rxd_d;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin rxd_s <= 1'b1; rxd_d <= 1'b1; end
    else begin rxd_s <= rxd; rxd_d <= rxd_s; end
  end
  wire start_det = rxd_d & ~rxd_s;

  typedef enum logic [1:0] {RX_IDLE, RX_START, RX_DATA, RX_STOP} rx_t;
  rx_t        rstate;
  logic [3:0] rsub, rbit;
  logic [7:0] rshift;

  assign rx_valid = (rstate == RX_STOP) && tick16 && (rsub == 4'd7);
  assign irq      = rx_valid;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rstate <= RX_IDLE; rsub <= '0; rbit <= '0;
      rshift <= '0; rx_data <= '0;
    end else case (rstate)
      RX_IDLE: if (start_det) begin
        rstate <= RX_START; rsub <= '0;
      end
      RX_START: if (tick16) begin
        if (rsub == 4'd7) begin
          rsub <= '0;
          rstate <= rxd_s ? RX_IDLE : RX_DATA;
        end else rsub <= rsub + 1'b1;
      end
      RX_DATA: if (tick16) begin
        if (rsub == 4'd15) begin
          rsub <= '0;
          rshift <= {rxd_s, rshift[7:1]};
          if (rbit == 4'd7) begin
            rbit <= '0;
            rx_data <= {rxd_s, rshift[7:1]};
            rstate <= RX_STOP;
          end else rbit <= rbit + 1'b1;
        end else rsub <= rsub + 1'b1;
      end
      RX_STOP: if (tick16) begin
        if (rsub == 4'd7) begin          // half stop bit: return to IDLE sooner
          rsub <= '0;
          rstate <= RX_IDLE;
        end else rsub <= rsub + 1'b1;
      end
      default: rstate <= RX_IDLE;
    endcase
  end

endmodule
