// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// CoreSight ATB slave: atvalid/atready handshake, 32-bit data + 7-bit ID
// Sink with 16-deep FIFO capture; fifo flush on atid change or AFREADY.
// OpenCreensight/atb funnel style.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module ATB_top #(
  parameter int DW = 32,
  parameter int DEPTH = 16
)(
  input  logic            clk,
  input  logic            rst_n,
  input  logic            atvalid,
  output logic            atready,
  input  logic [DW-1:0]   atdata,
  input  logic [6:0]      atid,
  input  logic            atlast,
  input  logic            afvalid,
  output logic            afready,
  input  logic            ren,
  input  logic [3:0]      raddr,
  output logic [DW-1:0]   rdata,
  output logic [4:0]      count,
  output logic [6:0]      last_id,
  output logic            irq
);
  logic [DW-1:0] mem [0:DEPTH-1];
  logic [4:0]    wr_ptr;
  logic [6:0]    cur_id;
  logic          id_change;

  assign atready = (wr_ptr < DEPTH);
  assign afready = 1'b1;                     // always accept flush
  assign count   = wr_ptr;
  assign irq     = atvalid && atready && atlast;

  // flush FIFO when AFVALID with new ID (simplified funnel behavior)
  assign id_change = afvalid && (atid != cur_id);

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      wr_ptr <= '0; cur_id <= '0; last_id <= '0;
    end else begin
      if (id_change) begin
        wr_ptr <= '0;                 // flush on id change
        cur_id <= atid;
      end else if (atvalid && atready) begin
        mem[wr_ptr[3:0]] <= atdata;
        wr_ptr <= wr_ptr + 1'b1;
        if (atlast) last_id <= atid;
      end
    end
  end

  assign rdata = mem[raddr[3:0]];

endmodule
