// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// Avalon-ST sink with 16-deep FIFO capture (valid/ready/data/eop)
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module Avalon_ST_top #(
  parameter int DW    = 32,
  parameter int DEPTH = 16
)(
  input  logic            clk,
  input  logic            rst_n,
  input  logic            av_valid,
  output logic            av_ready,
  input  logic [DW-1:0]   av_data,
  input  logic            av_eop,
  input  logic            ren,
  input  logic [3:0]      raddr,
  output logic [DW-1:0]   rdata,
  output logic [4:0]      count,
  output logic            irq
);
  logic [DW-1:0] mem [0:DEPTH-1];
  logic [4:0]    wr_ptr;

  assign av_ready = (wr_ptr < DEPTH);
  assign count    = wr_ptr;
  assign irq      = av_valid && av_ready && av_eop;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      wr_ptr <= '0;
    end else if (av_valid && av_ready) begin
      mem[wr_ptr[3:0]] <= av_data;
      wr_ptr           <= wr_ptr + 1'b1;
    end
  end

  assign rdata = mem[raddr];

endmodule
