// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// AXI-Stream sink monitor with 16-deep FIFO capture
// OpenCores avalon/peripheral style: tready backpressure, IRQ on tlast.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module AXI_Stream_top #(
  parameter int DW    = 32,
  parameter int DEPTH = 16
)(
  input  logic            clk,
  input  logic            rst_n,
  input  logic            tvalid,
  output logic            tready,
  input  logic [DW-1:0]   tdata,
  input  logic            tlast,
  input  logic            ren,
  input  logic [3:0]      raddr,
  output logic [DW-1:0]   rdata,
  output logic [4:0]      count,
  output logic            irq
);
  logic [DW-1:0] mem [0:DEPTH-1];
  logic [4:0]    wr_ptr;

  assign tready = (wr_ptr < DEPTH);
  assign push   = tvalid && tready;
  assign count  = wr_ptr;
  assign irq    = push && tlast;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      wr_ptr <= '0;
    end else begin
      if (push) begin
        mem[wr_ptr[3:0]] <= tdata;
        wr_ptr           <= wr_ptr + 1'b1;
      end
    end
  end

  assign rdata = mem[raddr];

endmodule
