// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// FlexRay simplified static-slot frame.
// - TX: bit stuffing (after 5 consecutive equal bits), CRC-15 (poly 0x4599)
// - RX: hard sync on SOF edge, de-stuffing, CRC check, ACK drive
// - Bus timing: 2 timer phases per bit; TX drives at phase 0, RX samples at 1
// Style follows OpenCores can_controller basics.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module FlexRay_top #(
  parameter int BAUD_DIV = 50              // clk cycles per phase
)(
  input  logic        clk,
  input  logic        rst_n,
  input  logic        rxd,
  output logic        txd,
  input  logic        wen,
  input  logic [3:0]  waddr,   // 0: id[7:0]  1: {id[10:8],1'b0,dlc[3:0]}
  input  logic [7:0]  wdata,   // 2-9: data   10: go
  input  logic        ren,
  input  logic [3:0]  raddr,   // 0: rx id[7:0] 1: {rx_id[10:8],1'b0,rx_dlc}
  output logic [7:0]  rdata,   // 2-9: rx data  10: status
  output logic        irq
);
  // ---------------- registers ----------------
  logic [10:0] tx_id;
  logic [3:0]  tx_dlc;
  logic [7:0]  tx_mem [0:7];
  logic        tx_go, tx_busy;

  // ---------------- bit timer (2 phases per bit) ----------------
  logic [15:0] tmr;
  logic        phase;
  wire         tick = (tmr == BAUD_DIV-1);
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin tmr <= '0; phase <= 1'b0; end
    else if (tick) begin tmr <= '0; phase <= ~phase; end
    else tmr <= tmr + 1'b1;
  end

  function automatic logic [14:0] crc_next(input logic [14:0] c, input logic b);
    logic fb;
    begin
      fb = b ^ c[14];
      crc_next = {c[13:0], 1'b0} ^ (fb ? 15'h4599 : 15'h0);
    end
  endfunction

  // ---------------- TX ----------------
  typedef enum logic [3:0] {
    TX_IDLE, TX_HDR, TX_DATA, TX_CRC, TX_CRCD, TX_ACK, TX_ACKD, TX_EOF
  } tx_t;
  tx_t        tstate;
  logic [4:0] tx_bit;
  logic [2:0] tx_byte;
  logic [17:0] tx_hdr;      // {id[10:0], rtr=0, ide=0, r0=0, dlc[3:0]}
  logic [14:0] tx_crc;
  logic [3:0]  run_cnt;
  logic        prev_bit;
  logic        can_out;

  wire [7:0]  tx_data_b = tx_mem[tx_byte];
  wire        tx_field_bit = (tstate == TX_HDR)  ? tx_hdr[17-tx_bit] :
                             (tstate == TX_DATA) ? tx_data_b[7-tx_bit[2:0]] :
                                                   tx_crc[14-tx_bit];

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      tstate <= TX_IDLE; tx_bit <= '0; tx_byte <= '0; run_cnt <= '0;
      prev_bit <= 1'b1; tx_crc <= '0; can_out <= 1'b1; tx_busy <= 1'b0;
      tx_go <= 1'b0; tx_id <= '0; tx_dlc <= '0;
      for (int i = 0; i < 8; i++) tx_mem[i] <= '0;
    end else begin
      if (wen && waddr == 4'd0) tx_id[7:0] <= wdata;
      if (wen && waddr == 4'd1) begin tx_id[10:8] <= wdata[7:5]; tx_dlc <= wdata[3:0]; end
      if (wen && waddr >= 4'd2 && waddr <= 4'd9) tx_mem[waddr[3:0] - 4'd2] <= wdata;
      if (wen && waddr == 4'd10 && wdata[0]) tx_go <= 1'b1;

      if (tick && !phase) begin                 // drive point
        case (tstate)
          TX_IDLE: if (tx_go) begin
            tx_go   <= 1'b0;
            tx_busy <= 1'b1;
            tx_hdr  <= {tx_id, 1'b0, 1'b0, 1'b0, tx_dlc};
            tx_crc  <= '0;
            run_cnt <= 4'd1;                    // SOF = first dominant bit
            prev_bit <= 1'b0;
            can_out <= 1'b0;                    // SOF
            tx_bit  <= '0; tx_byte <= '0;
            tstate  <= TX_HDR;
          end
          TX_HDR, TX_DATA, TX_CRC: begin
            if (run_cnt == 4'd5) begin
              // send stuff bit (opposite of previous); field not advanced
              can_out  <= ~prev_bit;
              prev_bit <= ~prev_bit;
              run_cnt  <= 4'd1;
            end else begin
              can_out <= tx_field_bit;
              if (tstate != TX_CRC)             // CRC over SOF..data (SOF adds 0: no-op)
                tx_crc <= crc_next(tx_crc, tx_field_bit);
              if (tx_field_bit == prev_bit) run_cnt <= run_cnt + 1'b1;
              else run_cnt <= 4'd1;
              prev_bit <= tx_field_bit;
              if (tstate == TX_HDR) begin
                if (tx_bit == 5'd17) begin
                  tx_bit <= '0;
                  tstate <= (tx_dlc == 0) ? TX_CRC : TX_DATA;
                end else tx_bit <= tx_bit + 1'b1;
              end else if (tstate == TX_DATA) begin
                if (tx_bit[2:0] == 3'd7) begin
                  tx_bit <= '0;
                  if (tx_byte == tx_dlc[2:0] - 3'd1) tstate <= TX_CRC;
                  else tx_byte <= tx_byte + 1'b1;
                end else tx_bit <= tx_bit + 1'b1;
              end else begin
                if (tx_bit == 5'd14) begin tx_bit <= '0; tstate <= TX_CRCD; end
                else tx_bit <= tx_bit + 1'b1;
              end
            end
          end
          TX_CRCD: begin can_out <= 1'b1; tstate <= TX_ACK; end
          TX_ACK:  begin can_out <= 1'b1; tstate <= TX_ACKD; end   // release for ACK
          TX_ACKD: begin can_out <= 1'b1; tstate <= TX_EOF; tx_bit <= '0; end
          TX_EOF: begin
            can_out <= 1'b1;
            if (tx_bit == 5'd6) begin
              tx_bit <= '0; tstate <= TX_IDLE; tx_busy <= 1'b0;
            end else tx_bit <= tx_bit + 1'b1;
          end
          default: tstate <= TX_IDLE;
        endcase
      end
    end
  end

  // ---------------- RX ----------------
  typedef enum logic [3:0] {
    RX_IDLE, RX_HDR, RX_DATA, RX_CRC, RX_CRCD, RX_ACK, RX_ACKD, RX_EOF
  } rx_t;
  rx_t         rstate;
  logic [4:0]  rx_bit;
  logic [2:0]  rx_byte;
  logic [17:0] rx_hdr_sh;
  logic [10:0] rx_id;
  logic [3:0]  rx_dlc;
  logic [7:0]  rx_mem [0:7];
  logic [14:0] rx_crc;
  logic [3:0]  rx_run;        // consecutive equal received bits
  logic        last_rx;       // last received bit (stuff bits included)
  logic        rx_bit_v;      // destuffed bit valid (pulse)
  logic        rx_err, rx_valid;
  logic        ack_drive;
  logic        rxed, rxed_d;
  logic        sof_wait;      // next sample is the SOF bit itself

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin rxed <= 1'b1; rxed_d <= 1'b1; end
    else begin rxed <= rxd; rxed_d <= rxed; end
  end
  wire sof_det = rxed_d & ~rxed;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rstate <= RX_IDLE; rx_bit <= '0; rx_byte <= '0; rx_run <= '0;
      rx_crc <= '0; rx_bit_v <= 1'b0; rx_err <= 1'b0; rx_valid <= 1'b0;
      ack_drive <= 1'b0; last_rx <= 1'b1; rx_hdr_sh <= '0; sof_wait <= 1'b0;
      rx_id <= '0; rx_dlc <= '0;
      for (int i = 0; i < 8; i++) rx_mem[i] <= '0;
    end else begin
      rx_bit_v <= 1'b0;
      rx_valid <= 1'b0;

      if (sof_det && rstate == RX_IDLE && !sof_wait) begin
        // hard sync: SOF edge; consume SOF immediately (it is dominant)
        rstate   <= RX_HDR;
        rx_bit   <= '0; rx_byte <= '0; rx_run <= 4'd1; last_rx <= 1'b0;
        rx_crc   <= '0;                 // crc_next(*,0) on all-zero state = 0
        rx_err   <= 1'b0;
        sof_wait <= 1'b1;               // skip the mid-SOF sample (same bit)
      end

      if (tick && phase && rstate != RX_IDLE) begin
        if (sof_wait) begin
          sof_wait <= 1'b0;             // mid-SOF sample: already consumed
        end else if (rstate == RX_HDR || rstate == RX_DATA || rstate == RX_CRC) begin
          if (rx_run == 4'd5) begin
            // stuff bit: discard. It still counts as 1 received bit (it breaks
            // the run), so TX/RX run counters stay aligned.
            rx_run   <= 4'd1;
            last_rx  <= rxed;
          end else begin
            rx_bit_v <= 1'b1;
            if (rxed == last_rx) rx_run <= rx_run + 1'b1;
            else rx_run <= 4'd1;
            last_rx <= rxed;
          end
        end else begin
          rx_bit_v <= 1'b1;             // CRC delim / ACK / EOF: no stuffing
        end
      end

      if (rx_bit_v) begin
        case (rstate)
          RX_HDR: begin
            rx_hdr_sh <= {rx_hdr_sh[16:0], rxed};
            rx_crc    <= crc_next(rx_crc, rxed);
            if (rx_bit == 5'd17) begin
              rx_id  <= rx_hdr_sh[16:6];          // id[10:0] = hdr[17:7]
              rx_dlc <= {rx_hdr_sh[2:0], rxed};   // dlc[3:0] = hdr[3:0]
              rx_bit <= '0;
              rstate <= ({rx_hdr_sh[2:0], rxed} == 4'd0) ? RX_CRC : RX_DATA;
            end else rx_bit <= rx_bit + 1'b1;
          end
          RX_DATA: begin
            rx_mem[rx_byte][7-rx_bit[2:0]] <= rxed;
            rx_crc <= crc_next(rx_crc, rxed);
            if (rx_bit[2:0] == 3'd7) begin
              rx_bit <= '0;
              if (rx_byte == rx_dlc[2:0] - 3'd1) rstate <= RX_CRC;
              else rx_byte <= rx_byte + 1'b1;
            end else rx_bit <= rx_bit + 1'b1;
          end
          RX_CRC: begin
            if (rx_bit < 5'd15 && rxed != rx_crc[14-rx_bit]) rx_err <= 1'b1;
            if (rx_bit == 5'd14) begin rx_bit <= '0; rstate <= RX_CRCD; end
            else rx_bit <= rx_bit + 1'b1;
          end
          RX_CRCD: begin rx_bit <= '0; rstate <= RX_ACK; ack_drive <= !rx_err; end
          RX_ACK:  begin ack_drive <= 1'b0; rstate <= RX_ACKD; end
          RX_ACKD: rstate <= RX_EOF;
          RX_EOF: begin
            if (rx_bit == 5'd6) begin
              rx_bit <= '0; rstate <= RX_IDLE;
              if (!rx_err) rx_valid <= 1'b1;
            end else rx_bit <= rx_bit + 1'b1;
          end
          default: ;
        endcase
      end
    end
  end

  assign txd = can_out & ~ack_drive;   // RX ACK dominant-overrides during ACK slot
  assign irq = rx_valid;

  assign rdata = (raddr == 4'd0)  ? rx_id[7:0] :
                 (raddr == 4'd1)  ? {rx_id[10:8], 1'b0, rx_dlc} :
                 (raddr >= 4'd2 && raddr <= 4'd9) ? rx_mem[raddr[3:0] - 4'd2] :
                 (raddr == 4'd10) ? {2'b00, rx_err, 1'b0, 1'b0, tx_busy, 2'b00} :
                                    8'h00;

endmodule
