// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// GMII MAC datapath: 8-bit SDR TX + RX with FIFOs
// TX: bytes from host FIFO -> txd/tx_en on tx_clk; RX: rxd/rx_dv -> FIFO
// Loopback-compatible. OpenCores ethernet/mac style.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module GMII_top #(
  parameter int DEPTH = 16
)(
  input  logic       clk,
  input  logic       rst_n,
  input  logic       tx_clk,
  output logic [7:0] txd,
  output logic       tx_en,
  output logic       tx_er,
  input  logic       rx_clk,
  input  logic [7:0] rxd,
  input  logic       rx_dv,
  input  logic       rx_er,
  input  logic       wen,
  input  logic [3:0] waddr,
  input  logic [7:0] wdata,
  input  logic       ren,
  input  logic [3:0] raddr,
  output logic [7:0] rdata,
  output logic [4:0] count,
  output logic       irq
);
  logic [7:0] txq [0:7];
  logic [2:0] tx_wr, tx_rd;
  logic       txen_q;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin tx_wr <= '0; tx_rd <= '0; end
    else if (wen && waddr == 4'd0) begin
      txq[tx_wr] <= wdata;
      tx_wr <= tx_wr + 1'b1;
    end
  end

  always @(posedge tx_clk) begin
    if (!rst_n) begin
      txd <= 8'h0; txen_q <= 1'b0; tx_rd <= '0;
    end else if (tx_wr != tx_rd) begin
      txd <= txq[tx_rd];
      txen_q <= 1'b1;
      tx_rd <= tx_rd + 1'b1;
    end else begin
      txen_q <= 1'b0;
    end
  end
  assign tx_en = txen_q;
  assign tx_er = 1'b0;

  logic [7:0] rxq [0:DEPTH-1];
  logic [4:0] rx_wr;
  logic       rxclk_s, rxclk_d, rxdv_d;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin rxclk_s <= 1'b0; rxclk_d <= 1'b0; rxdv_d <= 1'b0; end
    else begin rxclk_s <= rx_clk; rxclk_d <= rxclk_s; rxdv_d <= rx_dv; end
  end
  wire rxv_rise = rxclk_s & ~rxclk_d;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin rx_wr <= '0; end
    else if (rxv_rise && rxdv_d) begin
      rxq[rx_wr[3:0]] <= rxd;
      rx_wr <= rx_wr + 1'b1;
    end
  end

  assign count = rx_wr;
  assign rdata = rxq[raddr[3:0]];
  assign irq   = (rx_wr != 0) && ren;

endmodule
