// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// GPIO bank: 8-bit bidirectional, per-bit output-enable, input readback
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module GPIO_top (
  input  logic       clk,
  input  logic       rst_n,
  input  logic       wen,
  input  logic [3:0] waddr,
  input  logic [7:0] wdata,
  input  logic       ren,
  input  logic [3:0] raddr,
  output logic [7:0] rdata,
  inout  tri  [7:0]  gpio,
  input  logic [7:0] gpio_oe,
  output logic       irq
);
  logic [7:0] out_q, in_q;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      out_q <= '0; in_q <= '0;
    end else begin
      if (wen && waddr == 4'd0) out_q <= wdata;
      in_q <= gpio;
    end
  end

  assign gpio  = gpio_oe ? out_q : 8'hzz;
  assign rdata = (raddr == 4'd0) ? in_q :
                 (raddr == 4'd1) ? out_q : 8'h00;
  assign irq   = |in_q;

endmodule
