// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// HBM3: 8-channel over the MEMCH_top multi-channel wrapper (PROTOCOL=9, NCH=8 (8-channel)).
// Educational slice of HBM3; gem5 trace port unchanged.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module HBM3_top (
  input  logic        clk,
  input  logic        rst_n,
  input  logic        hvalid,
  output logic        hready,
  input  logic [2:0]  hcmd,
  input  logic [31:0] haddr,
  input  logic [15:0] hwdata,
  output logic [15:0] hrdata,
  output logic        hdone,
  output logic        ck_t, ck_c,
    output logic [16:0] addr,
  output logic        ras_n, cas_n, we_n,

  inout  tri [127:0]   dq,
  inout  tri [1:0]    dqs,
  output logic        cke,
  output logic        trace_valid,
  output logic [2:0]  trace_cmd,
  output logic [31:0] trace_addr
);
  MEMCH_top #(.PROTOCOL(9), .NCH(8), .CL(16), .TRCD(8), .TRP(8)) core (.*);
endmodule
