// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// HBM4: 16-channel over the MEMCH_top multi-channel wrapper (PROTOCOL=11, NCH=16 (16-channel)).
// Educational slice of HBM4; gem5 trace port unchanged.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module HBM4_top (
  input  logic        clk,
  input  logic        rst_n,
  input  logic        hvalid,
  output logic        hready,
  input  logic [2:0]  hcmd,
  input  logic [31:0] haddr,
  input  logic [15:0] hwdata,
  output logic [15:0] hrdata,
  output logic        hdone,
  output logic        ck_t, ck_c,
    output logic [16:0] addr,
  output logic        ras_n, cas_n, we_n,

  inout  tri [255:0]   dq,
  inout  tri [1:0]    dqs,
  output logic        cke,
  output logic        trace_valid,
  output logic [2:0]  trace_cmd,
  output logic [31:0] trace_addr
);
  MEMCH_top #(.PROTOCOL(11), .NCH(16), .CL(12), .TRCD(6), .TRP(6)) core (.*);
endmodule
