// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// I2C slave: START/STOP detect, 7-bit address match, ACK, byte RX/TX
// Open-drain SDA (drive low / release). All logic in clk domain with
// synchronized SCL/SDA edge detection.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module I2C_top #(
  parameter int I2C_ADDR = 7'h50
)(
  input  logic       clk,
  input  logic       rst_n,
  inout  tri         sda,
  input  logic       scl,
  input  logic [7:0] tx_byte,    // data to send in read mode
  output logic [7:0] rx_byte,    // last byte received in write mode
  output logic       rx_valid,   // 1-clk pulse per received byte
  output logic       busy,
  output logic       irq
);
  // ---------------- input synchronization ----------------
  logic scl_s, scl_d, sda_s, sda_d;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      scl_s <= 1'b1; scl_d <= 1'b1; sda_s <= 1'b1; sda_d <= 1'b1;
    end else begin
      scl_s <= scl; scl_d <= scl_s;
      sda_s <= sda; sda_d <= sda_s;
    end
  end
  wire scl_rise  =  scl_s & ~scl_d;
  wire scl_fall  = ~scl_s &  scl_d;
  wire start_det = ~sda_s &  sda_d & scl_s;   // SDA falls while SCL high
  wire stop_det  =  sda_s & ~sda_d & scl_s;   // SDA rises while SCL high

  // ---------------- FSM ----------------
  typedef enum logic [2:0] {
    ST_IDLE, ST_ADDR, ST_ACK, ST_RX, ST_TX, ST_TXACK, ST_IGNORE
  } st_t;
  st_t      state;
  logic [3:0] bit_cnt;
  logic [7:0] shift;
  logic       rw, ack_low, txack_done;

  assign sda     = ack_low ? 1'b0 : 1'bz;
  assign busy    = (state != ST_IDLE) && (state != ST_IGNORE);
  assign irq     = rx_valid;

  wire [7:0] addr_byte = {shift[6:0], sda_s};   // byte assembled on 8th bit

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= ST_IDLE; bit_cnt <= '0; shift <= '0;
      rw <= 1'b0; ack_low <= 1'b0; txack_done <= 1'b0;
      rx_byte <= '0; rx_valid <= 1'b0;
    end else begin
      rx_valid <= 1'b0;
      if (start_det) begin
        state <= ST_ADDR; bit_cnt <= '0; ack_low <= 1'b0; txack_done <= 1'b0;
      end else if (stop_det) begin
        state <= ST_IDLE; ack_low <= 1'b0; txack_done <= 1'b0;
      end else case (state)
        // -------- address phase --------
        ST_ADDR: if (scl_rise) begin
          shift <= addr_byte;
          if (bit_cnt == 4'd7) begin
            bit_cnt <= '0;
            if (addr_byte[7:1] == I2C_ADDR[6:0]) begin
              rw   <= addr_byte[0];
              state <= ST_ACK;          // ACK will be driven on next SCL fall
            end else begin
              state <= ST_IGNORE;       // not us: release SDA
            end
          end else begin
            bit_cnt <= bit_cnt + 1'b1;
          end
        end

        // -------- ACK bit: drive SDA low between 8th-bit fall and 9th-bit fall --------
        ST_ACK: begin
          if (!ack_low) begin
            if (scl_fall) ack_low <= 1'b1;
          end else if (scl_fall) begin
            ack_low <= 1'b0;
            if (rw) begin
              // present MSB of first byte at this fall (last NBA wins)
              ack_low <= (tx_byte[7] == 1'b0);
              state <= ST_TX;
            end else begin
              state <= ST_RX;           // release SDA for data phase
            end
          end
        end

        // -------- write: receive bytes --------
        ST_RX: if (scl_rise) begin
          shift <= addr_byte;
          if (bit_cnt == 4'd7) begin
            rx_byte  <= addr_byte;
            rx_valid <= 1'b1;
            bit_cnt  <= '0;
            state    <= ST_ACK;         // ACK each received byte
          end else begin
            bit_cnt <= bit_cnt + 1'b1;
          end
        end

        // -------- read: transmit tx_byte MSB-first --------
        ST_TX: if (scl_fall) begin
          if (bit_cnt == 4'd7) begin
            bit_cnt <= '0;
            ack_low <= 1'b0;            // release SDA for master ACK
            state   <= ST_TXACK;
          end else begin
            bit_cnt <= bit_cnt + 1'b1;
            // present next bit after this fall (valid at next rise)
            ack_low <= (tx_byte[6-bit_cnt] == 1'b0);
          end
        end

        // -------- master ACK/NACK after 8 transmitted bits --------
        ST_TXACK: begin
          if (!txack_done) begin
            if (scl_rise) begin
              txack_done <= 1'b1;
              if (sda_s == 1'b1) begin
                state <= ST_IDLE;       // NACK: transaction done
              end
            end
          end else if (scl_fall) begin
            txack_done <= 1'b0;
            if (state == ST_TXACK) begin
              bit_cnt <= '0;
              ack_low <= (tx_byte[7] == 1'b0);   // ACKed: present first bit
              state   <= ST_TX;
            end
          end
        end

        default: ;  // ST_IGNORE, ST_IDLE: wait for START/STOP
      endcase
    end
  end

endmodule
