// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// I2S slave transmitter/receiver, 16-bit samples, 2 channels
// Samples SDIN on BCLK rise, shifts SDOUT on BCLK fall (I2S standard).
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module I2S_top #(
  parameter int DW = 16
)(
  input  logic            clk,
  input  logic            rst_n,
  input  logic            bclk,
  input  logic            lrck,      // 0 = left, 1 = right
  input  logic            sdin,
  output logic            sdout,
  input  logic            wen,
  input  logic [3:0]      waddr,     // 0: tx_left, 1: tx_right
  input  logic [DW-1:0]   wdata,
  input  logic            ren,
  input  logic [3:0]      raddr,     // 0: rx_left, 1: rx_right
  output logic [DW-1:0]   rdata,
  output logic            irq        // frame-sync (LRCK change) pulse
);
  logic [DW-1:0] tx_left, tx_right, rx_left, rx_right;
  logic [DW-1:0] tx_shift, rx_shift;
  logic [4:0]    bit_cnt;
  logic          bclk_s, bclk_d, lrck_s, lrck_d;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      bclk_s <= 1'b0; bclk_d <= 1'b0;
      lrck_s <= 1'b0; lrck_d <= 1'b0;
    end else begin
      bclk_s <= bclk; bclk_d <= bclk_s;
      lrck_s <= lrck; lrck_d <= lrck_s;
    end
  end
  wire bclk_rise   =  bclk_s & ~bclk_d;
  wire bclk_fall   = ~bclk_s &  bclk_d;
  wire lrck_change =  lrck_s ^  lrck_d;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      tx_left <= '0; tx_right <= '0;
      rx_left <= '0; rx_right <= '0;
    end else begin
      if (wen && waddr == 4'd0) tx_left  <= wdata;
      if (wen && waddr == 4'd1) tx_right <= wdata;
      if (bclk_rise && bit_cnt == DW-1) begin
        if (!lrck_s) rx_left  <= {rx_shift[DW-2:0], sdin};
        else         rx_right <= {rx_shift[DW-2:0], sdin};
      end
    end
  end

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      tx_shift <= '0; rx_shift <= '0; bit_cnt <= '0;
    end else if (lrck_change) begin
      bit_cnt  <= '0;
      tx_shift <= lrck_s ? tx_right : tx_left;   // reload new channel
    end else begin
      if (bclk_rise)
        bit_cnt <= (bit_cnt == DW-1) ? '0 : bit_cnt + 1'b1;
      if (bclk_rise)
        rx_shift <= {rx_shift[DW-2:0], sdin};
      if (bclk_fall)
        tx_shift <= {tx_shift[DW-2:0], 1'b0};
    end
  end

  assign sdout = tx_shift[DW-1];
  assign rdata = (raddr == 4'd0) ? rx_left :
                 (raddr == 4'd1) ? rx_right : '0;
  assign irq   = lrck_change;

endmodule
