// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// I3C slave (SDR-compatible I2C framing) + in-band interrupt request (IBI)
// Reuses the I2C two-wire base; int_n is asserted after a write transaction
// (interrupt pending) and released by the next START (master acknowledges IBI).
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module I3C_top #(
  parameter int I3C_ADDR = 7'h2A
)(
  input  logic       clk,
  input  logic       rst_n,
  inout  tri         sda,
  input  logic       scl,
  input  logic [7:0] tx_byte,
  output logic [7:0] rx_byte,
  output logic       rx_valid,
  output logic       int_n,        // IBI request (low = pending)
  output logic       busy,
  output logic       irq
);
  logic scl_s, scl_d, sda_s, sda_d;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      scl_s <= 1'b1; scl_d <= 1'b1; sda_s <= 1'b1; sda_d <= 1'b1;
    end else begin
      scl_s <= scl; scl_d <= scl_s;
      sda_s <= sda; sda_d <= sda_s;
    end
  end
  wire scl_rise  =  scl_s & ~scl_d;
  wire scl_fall  = ~scl_s &  scl_d;
  wire start_det = ~sda_s &  sda_d & scl_s;
  wire stop_det  =  sda_s & ~sda_d & scl_s;

  typedef enum logic [2:0] {ST_IDLE, ST_ADDR, ST_ACK, ST_RX, ST_TX, ST_TXACK, ST_IGNORE} st_t;
  st_t      state;
  logic [3:0] bit_cnt;
  logic [7:0] shift;
  logic       rw, ack_low, txack_done;

  assign sda  = ack_low ? 1'b0 : 1'bz;
  assign busy = (state != ST_IDLE) && (state != ST_IGNORE);
  assign irq  = rx_valid;

  wire [7:0] byte_w = {shift[6:0], sda_s};

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= ST_IDLE; bit_cnt <= '0; shift <= '0;
      rw <= 1'b0; ack_low <= 1'b0; txack_done <= 1'b0;
      rx_byte <= '0; rx_valid <= 1'b0; int_n <= 1'b1;
    end else begin
      rx_valid <= 1'b0;
      if (start_det) begin
        state <= ST_ADDR; bit_cnt <= '0; ack_low <= 1'b0;
        int_n <= 1'b1;                       // START clears pending IBI
      end else if (stop_det) begin
        state <= ST_IDLE; ack_low <= 1'b0;
        if (state == ST_RX || rx_valid) int_n <= 1'b0;  // write done: request IBI
      end else case (state)
        ST_ADDR: if (scl_rise) begin
          shift <= byte_w;
          if (bit_cnt == 4'd7) begin
            bit_cnt <= '0;
            if (byte_w[7:1] == I3C_ADDR[6:0]) begin
              rw <= byte_w[0]; state <= ST_ACK;
            end else state <= ST_IGNORE;
          end else bit_cnt <= bit_cnt + 1'b1;
        end
        ST_ACK: begin
          if (!ack_low) begin
            if (scl_fall) ack_low <= 1'b1;
          end else if (scl_fall) begin
            ack_low <= 1'b0;
            state <= rw ? ST_TX : ST_RX;
          end
        end
        ST_RX: if (scl_rise) begin
          shift <= byte_w;
          if (bit_cnt == 4'd7) begin
            rx_byte <= byte_w; rx_valid <= 1'b1;
            bit_cnt <= '0; state <= ST_ACK;
          end else bit_cnt <= bit_cnt + 1'b1;
        end
        ST_TX: if (scl_fall) begin
          if (bit_cnt == 4'd7) begin
            bit_cnt <= '0; ack_low <= 1'b0; state <= ST_TXACK;
          end else begin
            bit_cnt <= bit_cnt + 1'b1;
            ack_low <= (tx_byte[6-bit_cnt] == 1'b0);
          end
        end
        ST_TXACK: begin
          if (!txack_done) begin
            if (scl_rise) begin
              txack_done <= 1'b1;
              if (sda_s == 1'b1) state <= ST_IDLE;   // NACK
            end
          end else if (scl_fall) begin
            txack_done <= 1'b0;
            if (state == ST_TXACK) begin
              bit_cnt <= '0;
              ack_low <= (tx_byte[7] == 1'b0);
              state   <= ST_TX;
            end
          end
        end
        default: ;
      endcase
    end
  end

endmodule
