// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// JTAG TAP controller, IEEE 1149.1
// 16-state FSM in TCK domain; IDCODE / BYPASS / USER data registers.
// Style follows classic OpenCores jtag/openjtag TAP cores.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module JTAG_top #(
  parameter logic [31:0] IDCODE = 32'h1CAF_0001
)(
  input  logic clk,
  input  logic rst_n,
  input  logic tck,
  input  logic tms,
  input  logic tdi,
  input  logic trst_n,
  output logic tdo,
  output logic irq
);
  // ---------------- TAP FSM (TCK domain) ----------------
  typedef enum logic [3:0] {
    TLR = 4'd0,  RTI,      SEL_DR, CAP_DR,
    SH_DR,       EX1_DR,   PAUSE_DR, EX2_DR,
    UPD_DR,      SEL_IR,   CAP_IR,   SH_IR,
    EX1_IR,      PAUSE_IR, EX2_IR,   UPD_IR
  } tap_t;
  tap_t tap_q;

  always_ff @(posedge tck or negedge trst_n) begin
    if (!trst_n) tap_q <= TLR;
    else case (tap_q)
      TLR:      tap_q <= tms ? TLR     : RTI;
      RTI:      tap_q <= tms ? SEL_DR  : RTI;
      SEL_DR:   tap_q <= tms ? SEL_IR  : CAP_DR;
      CAP_DR:   tap_q <= tms ? EX1_DR  : SH_DR;
      SH_DR:    tap_q <= tms ? EX1_DR  : SH_DR;
      EX1_DR:   tap_q <= tms ? UPD_DR  : PAUSE_DR;
      PAUSE_DR: tap_q <= tms ? EX2_DR  : PAUSE_DR;
      EX2_DR:   tap_q <= tms ? UPD_DR  : SH_DR;
      UPD_DR:   tap_q <= tms ? SEL_DR  : RTI;
      SEL_IR:   tap_q <= tms ? TLR     : CAP_IR;
      CAP_IR:   tap_q <= tms ? EX1_IR  : SH_IR;
      SH_IR:    tap_q <= tms ? EX1_IR  : SH_IR;
      EX1_IR:   tap_q <= tms ? UPD_IR  : PAUSE_IR;
      PAUSE_IR: tap_q <= tms ? EX2_IR  : PAUSE_IR;
      EX2_IR:   tap_q <= tms ? UPD_IR  : SH_IR;
      UPD_IR:   tap_q <= tms ? SEL_DR  : RTI;
      default:  tap_q <= TLR;
    endcase
  end

  // ---------------- instruction + data registers ----------------
  localparam logic [3:0] IR_IDCODE = 4'b0001;
  localparam logic [3:0] IR_USER   = 4'b0010;
  localparam logic [3:0] IR_BYPASS = 4'b1111;

  logic [3:0]  ir_q, sh_ir;
  logic        sh_byp;
  logic [7:0]  user_q, sh_user;
  logic [31:0] sh_id;

  // posedge TCK: FSM (tap_q), chain capture, IR/DR update
  always_ff @(posedge tck or negedge trst_n) begin
    if (!trst_n) begin
      ir_q <= IR_BYPASS; sh_ir <= '0; sh_byp <= 1'b0;
      user_q <= '0; sh_user <= '0; sh_id <= '0;
    end else begin
      if (tap_q == CAP_IR) sh_ir <= 4'b0101;              // capture pattern
      if (tap_q == UPD_IR) ir_q  <= sh_ir;
      if (tap_q == CAP_DR) begin
        case (ir_q)
          IR_IDCODE: sh_id   <= IDCODE;
          IR_USER:   sh_user <= user_q;
          default:   sh_byp  <= 1'b0;
        endcase
      end
      if (tap_q == UPD_DR && ir_q == IR_USER) user_q <= sh_user;
    end
  end

  // posedge TCK in Shift state: TDO <= pre-shift LSB; chain shifts (TDI in).
  // Master samples TDO after the falling edge -> sees bit shifted out this edge.
  wire cur_lsb = (tap_q == SH_IR) ? sh_ir[0] :
                 (ir_q == IR_IDCODE) ? sh_id[0] :
                 (ir_q == IR_USER)   ? sh_user[0] : sh_byp;
  logic tdo_q;
  always_ff @(posedge tck or negedge trst_n) begin
    if (!trst_n) begin
      tdo_q <= 1'b0; sh_ir <= '0;
    end else if (tap_q == SH_IR) begin
      tdo_q <= cur_lsb;
      sh_ir <= {tdi, sh_ir[3:1]};
    end
  end
  always_ff @(posedge tck or negedge trst_n) begin
    if (!trst_n) begin
      sh_id <= '0; sh_user <= '0; sh_byp <= 1'b0;
    end else if (tap_q == SH_DR) begin
      tdo_q <= cur_lsb;
      case (ir_q)
        IR_IDCODE: sh_id   <= {tdi, sh_id[31:1]};
        IR_USER:   sh_user <= {tdi, sh_user[7:1]};
        default:   sh_byp  <= tdi;
      endcase
    end
  end

  assign tdo = tdo_q;
  assign irq = (tap_q == UPD_DR);

endmodule
