// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// LPDDR5X: 2-channel over the MEMCH_top multi-channel wrapper (PROTOCOL=5, NCH=2 (2-channel)).
// Educational slice of LPDDR5X; gem5 trace port unchanged.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module LPDDR5X_top (
  input  logic        clk,
  input  logic        rst_n,
  input  logic        hvalid,
  output logic        hready,
  input  logic [2:0]  hcmd,
  input  logic [31:0] haddr,
  input  logic [15:0] hwdata,
  output logic [15:0] hrdata,
  output logic        hdone,
  output logic        ck_t, ck_c,
    output logic [6:0]  ca,
  output logic        cs_n,

  inout  tri [31:0]   dq,
  inout  tri [1:0]    dqs,
  output logic        cke,
  output logic        trace_valid,
  output logic [2:0]  trace_cmd,
  output logic [31:0] trace_addr
);
  logic [16:0] addr_full;
  logic ras_n, cas_n, we_n;

  MEMCH_top #(.PROTOCOL(5), .NCH(2), .CL(15), .TRCD(4), .TRP(4)) core (
    .clk(clk), .rst_n(rst_n),
    .hvalid(hvalid), .hready(hready), .hcmd(hcmd), .haddr(haddr),
    .hwdata(hwdata), .hrdata(hrdata), .hdone(hdone),
    .ck_t(ck_t), .ck_c(ck_c), .addr(addr_full),
    .ras_n(ras_n), .cas_n(cas_n), .we_n(we_n),
    .dq(dq), .dqs(dqs), .cke(cke),
    .trace_valid(trace_valid), .trace_cmd(trace_cmd), .trace_addr(trace_addr));

  assign ca = {1'b0, ras_n, cas_n, we_n, addr_full[2:0]};
  assign cs_n = ras_n & cas_n & we_n;
endmodule
