// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// MDIO slave (IEEE 802.3 Clause 22 PHY management)
// ST(01) + OP(2) + PHYAD(5) + REGAD(5) + TA(2) + DATA(16), MSB first.
// Open-drain MDIO; read data driven from bit 14..29 window.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module MDIO_top #(
  parameter int PHY_ADDR = 5'h0C
)(
  input  logic        clk,
  input  logic        rst_n,
  inout  tri          mdio,
  input  logic        mdc,
  output logic        irq
);
  logic [15:0] regs [0:31];
  logic        mdc_s, mdc_d, mdio_s;
  logic        frame_act;
  logic        prev_bit;             // mdio sampled at previous mdc rising edge
  logic [5:0]  cnt;
  logic [31:0] shift;
  logic        read_frame, read_match;
  logic [4:0]  regad_q;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      mdc_s <= 1'b0; mdc_d <= 1'b0; mdio_s <= 1'b1;
    end else begin
      mdc_s <= mdc; mdc_d <= mdc_s;
      mdio_s <= mdio;
    end
  end
  wire mdc_rise = mdc_s & ~mdc_d;

  // read data drive window (TA released, DATA bits driven)
  wire [15:0] rd_reg = regs[regad_q];
  // DATA[15] must be on the line while cnt==14 (window between TA2 edge and
  // DATA[15] edge); master samples it at the cnt==14 rising edge.
  wire drive_low = read_match && (cnt >= 6'd14) && (cnt <= 6'd29)
                   && (rd_reg[5'd29 - cnt[4:0]] == 1'b0);
  assign mdio = drive_low ? 1'b0 : 1'bz;
  assign irq  = frame_act && (cnt == 6'd29);

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      frame_act <= 1'b0; cnt <= '0; shift <= '0; prev_bit <= 1'b1;
      read_frame <= 1'b0; read_match <= 1'b0; regad_q <= '0;
      for (int i = 0; i < 32; i++) regs[i] <= 16'h0000;
      regs[0] <= 16'h1140;              // PHY ID preset (like OpenCores eth phy)
    end else if (mdc_rise) begin
      if (!frame_act) begin
        // ST pattern: previous sampled bit 0, current sampled bit 1
        if (!prev_bit && mdio_s) begin
          frame_act <= 1'b1; cnt <= '0;
        end
        prev_bit <= mdio_s;
      end else if (cnt == 6'd29) begin
        prev_bit <= mdio_s;
        // frame complete: shift[28:0] holds first 29 frame bits, mdio_s is bit 30
        frame_act  <= 1'b0;
        read_frame <= 1'b0;
        read_match <= 1'b0;
        if (shift[28:27] == 2'b01 && shift[26:22] == PHY_ADDR[4:0]) begin
          regs[shift[21:17]] <= {shift[14:0], mdio_s};   // write
        end
      end else begin
        shift <= {shift[30:0], mdio_s};
        cnt   <= cnt + 1'b1;
        if (cnt == 6'd1) begin
          read_frame <= (mdio_s == 1'b0) && (shift[0] == 1'b1); // OP == 10
        end
        if (cnt == 6'd6) begin
          read_match <= read_frame && ({shift[3:0], mdio_s} == PHY_ADDR[4:0]);
        end
        if (cnt == 6'd11) begin
          regad_q <= {shift[3:0], mdio_s};
        end
      end
    end
  end

  // read-back mux for external register interface simplicity:
  // regs are internal; expose nothing else (Clause-22 PHY style)

endmodule
