// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// Parametric SDRAM controller: DDR4 / DDR5 / LPDDR4 / LPDDR5 variants
// Single bank (educational), command FSM: IDLE-ACT-RD/WR-PRE with tRCD/tRP/
// tCAS timing. gem5 co-verification trace port emits (cmd,addr) per activation
// in gem5 DRAMCtrl trace format ("0xADDR: activate/rd/wr 0xROW").
// OpenCores ddr3_ctrl / gem5 DRAMCtrl simplified style.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module MEMCORE_top #(
  parameter int PROTOCOL = 0,   // 0=DDR4 1=DDR5 2=LPDDR4 3=LPDDR5
  parameter int CL   = 15,      // CAS latency (clk)
  parameter int TRCD = 15,      // RAS->CAS
  parameter int TRP  = 15,      // PRE period
  parameter int AW   = 17       // addr width (LPDDR uses CA bus instead)
)(
  input  logic              clk,
  input  logic              rst_n,
  // host command interface
  input  logic              hvalid,
  output logic              hready,
  input  logic [2:0]        hcmd,     // 0=idle 1=ACT 2=RD 3=WR 4=PRE
  input  logic [31:0]       haddr,
  input  logic [15:0]       hwdata,
  output logic [15:0]       hrdata,
  output logic              hdone,
  // PHY pins
  output logic              ck_t,
  output logic              ck_c,
  output logic [AW-1:0]     addr,
  output logic              ras_n,
  output logic              cas_n,
  output logic              we_n,
  inout  tri [15:0]         dq,
  inout  tri [1:0]          dqs,
  output logic              cke,
  // gem5 co-verification trace port
  output logic              trace_valid,
  output logic [2:0]        trace_cmd,
  output logic [31:0]       trace_addr
);
  localparam int COLW = 8;
  localparam int ROWW = 14;

  // ---------------- memory array (single bank, word granular) ----------------
  (* ram_style = "block" *) logic [15:0] mem [0:(1<<COLW)-1];
  logic [ROWW-1:0] open_row;
  logic       bank_open;

  // ---------------- timings ----------------
  logic [7:0] timer;         // shared down-counter for tRCD/tRP/tCAS
  typedef enum logic [2:0] {D_IDLE, D_ACT, D_RCD, D_RD, D_CAS, D_WR, D_PRE} d_t;
  d_t dstate;
  logic [31:0] cur_addr;
  logic [15:0] wr_data;
  logic        rd_pending;

  assign ck_t = clk;
  assign ck_c = ~clk;
  assign cke  = rst_n;
  assign dqs  = 2'bzz;
  assign hready = (dstate == D_IDLE);
  assign hdone  = (dstate == D_CAS) && (timer == 0) && rd_pending;

  // gem5 trace
  assign trace_valid = (dstate == D_ACT) || (dstate == D_RD) || (dstate == D_WR);
  assign trace_cmd   = (dstate == D_ACT) ? 3'd1 :
                       (dstate == D_RD)  ? 3'd2 : 3'd3;
  assign trace_addr  = cur_addr;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      dstate <= D_IDLE; timer <= '0; open_row <= '0; bank_open <= 1'b0;
      cur_addr <= '0; wr_data <= '0; rd_pending <= 1'b0; hrdata <= '0;
      ras_n <= 1'b1; cas_n <= 1'b1; we_n <= 1'b1;
      for (int i = 0; i < (1<<COLW); i++) mem[i] <= 16'h0;
    end else begin
      if (timer != 0) timer <= timer - 1'b1;
      case (dstate)
        D_IDLE: if (hvalid) begin
          cur_addr <= haddr;
          wr_data  <= hwdata;
          rd_pending <= (hcmd == 3'd2);
          case (hcmd)
            3'd1: begin                 // ACT: open row
              dstate <= D_ACT;
              open_row <= haddr[31:18];
              bank_open <= 1'b1;
            end
            3'd2: begin                 // RD (row must be open)
              dstate <= D_RD;
            end
            3'd3: begin                 // WR
              dstate <= D_WR;
            end
            3'd4: begin                 // PRE
              dstate <= D_PRE;
            end
            default: ;
          endcase
        end
        D_ACT: begin
          // assert RAS, emit gem5 activate trace
          ras_n <= 1'b0; cas_n <= 1'b1; we_n <= 1'b1;
          addr  <= {{(AW-ROWW){1'b0}}, open_row};
          dstate <= D_RCD; timer <= TRCD[7:0];
        end
        D_RCD: begin
          ras_n <= 1'b1;
          if (timer == 0) dstate <= D_IDLE;   // back to host for RD/WR
        end
        D_RD: begin
          ras_n <= 1'b1; cas_n <= 1'b0; we_n <= 1'b1;
          addr  <= {{(AW-COLW){1'b0}}, cur_addr[COLW-1:0]};
          dstate <= D_CAS; timer <= CL[7:0];
        end
        D_WR: begin
          ras_n <= 1'b1; cas_n <= 1'b0; we_n <= 1'b0;
          addr  <= {{(AW-COLW){1'b0}}, cur_addr[COLW-1:0]};
          mem[cur_addr[COLW-1:0]] <= wr_data;
          dstate <= D_CAS; timer <= CL[7:0];
        end
        D_CAS: begin
          cas_n <= 1'b1; we_n <= 1'b1;
          if (timer == 0) begin
            if (rd_pending) hrdata <= mem[cur_addr[COLW-1:0]];
            rd_pending <= 1'b0;
            dstate <= D_IDLE;
          end
        end
        D_PRE: begin
          ras_n <= 1'b0; cas_n <= 1'b1; we_n <= 1'b0;
          bank_open <= 1'b0;
          dstate <= D_IDLE; timer <= TRP[7:0];
        end
        default: dstate <= D_IDLE;
      endcase
    end
  end

  // DQ: drive written data during WR, else Hi-Z (educational, no DQS timing)
  assign dq = (dstate == D_WR) ? wr_data : 16'hzzzz;

endmodule
