// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// MEMCH_top: generic N-channel memory controller wrapper.
// NCH instances of the parametric DDR4_top core share the command bus
// (channel 0 drives addr/RAS/CAS/WE, like a shared CAD bus); channel select
// comes from haddr[8 +: CHW]. Each channel owns dq[gi*16 +: 16].
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module MEMCH_top #(
  parameter int PROTOCOL = 0,
  parameter int NCH      = 2,
  parameter int CL       = 15,
  parameter int TRCD     = 15,
  parameter int TRP      = 15,
  parameter int AW       = 17
)(
  input  logic              clk,
  input  logic              rst_n,
  input  logic              hvalid,
  output logic              hready,
  input  logic [2:0]        hcmd,
  input  logic [31:0]       haddr,
  input  logic [15:0]       hwdata,
  output logic [15:0]       hrdata,
  output logic              hdone,
  output logic              ck_t, ck_c,
  output logic [AW-1:0]     addr,
  output logic              ras_n, cas_n, we_n,
  inout  tri [NCH*16-1:0]   dq,
  inout  tri [1:0]          dqs,
  output logic              cke,
  output logic              trace_valid,
  output logic [2:0]        trace_cmd,
  output logic [31:0]       trace_addr
);
  localparam int CHW = (NCH <= 2) ? 1 : $clog2(NCH);
  wire [CHW-1:0] sel = haddr[8 +: CHW];

  logic [15:0] hrdata_v [0:NCH-1];
  logic        hready_v [0:NCH-1];
  logic        hdone_v  [0:NCH-1];
  logic        tv_v     [0:NCH-1];
  logic [2:0]  tc_v     [0:NCH-1];
  logic [31:0] ta_v     [0:NCH-1];

  genvar gi;
  generate
    for (gi = 0; gi < NCH; gi++) begin : g_ch
      if (gi == 0) begin : g_drv
        // channel 0 drives the shared command bus (shared-CAD model)
        MEMCORE_top #(.PROTOCOL(PROTOCOL), .CL(CL), .TRCD(TRCD), .TRP(TRP), .AW(AW)) core (
          .clk(clk), .rst_n(rst_n),
          .hvalid(hvalid && ((NCH == 1) || (sel == gi[CHW-1:0]))),
          .hready(hready_v[gi]),
          .hcmd(hcmd), .haddr(haddr), .hwdata(hwdata),
          .hrdata(hrdata_v[gi]), .hdone(hdone_v[gi]),
          .ck_t(ck_t), .ck_c(ck_c), .addr(addr),
          .ras_n(ras_n), .cas_n(cas_n), .we_n(we_n),
          .dq(dq[gi*16 +: 16]), .dqs(dqs), .cke(cke),
          .trace_valid(tv_v[gi]), .trace_cmd(tc_v[gi]), .trace_addr(ta_v[gi]));
      end else begin : g_nd
        // other channels: shared pins left open (driven by ch0)
        MEMCORE_top #(.PROTOCOL(PROTOCOL), .CL(CL), .TRCD(TRCD), .TRP(TRP), .AW(AW)) core (
          .clk(clk), .rst_n(rst_n),
          .hvalid(hvalid && ((NCH == 1) || (sel == gi[CHW-1:0]))),
          .hready(hready_v[gi]),
          .hcmd(hcmd), .haddr(haddr), .hwdata(hwdata),
          .hrdata(hrdata_v[gi]), .hdone(hdone_v[gi]),
          .ck_t(), .ck_c(), .addr(),
          .ras_n(), .cas_n(), .we_n(),
          .dq(dq[gi*16 +: 16]), .dqs(), .cke(),
          .trace_valid(tv_v[gi]), .trace_cmd(tc_v[gi]), .trace_addr(ta_v[gi]));
      end
    end
  endgenerate

  assign hready      = hready_v[sel];
  assign hdone       = hdone_v[sel];
  assign hrdata      = hrdata_v[sel];
  assign trace_valid = tv_v[sel];
  assign trace_cmd   = tc_v[sel];
  assign trace_addr  = ta_v[sel];

endmodule
