// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// PWM generator: period/duty registers, active-high output + complement
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module PWM_top #(
  parameter int DW = 32
)(
  input  logic            clk,
  input  logic            rst_n,
  input  logic            wen,
  input  logic [3:0]      waddr,
  input  logic [DW-1:0]   wdata,
  output logic            pwm_out,
  output logic            pwm_n_out,
  output logic            irq
);
  logic [DW-1:0] period_q, duty_q, counter;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      period_q <= '0; duty_q <= '0; counter <= '0;
    end else begin
      if (wen && waddr == 4'd0) period_q <= wdata;
      if (wen && waddr == 4'd1) duty_q   <= wdata;
      if (period_q != 0)
        counter <= (counter >= period_q - 1'b1) ? '0 : counter + 1'b1;
      else
        counter <= '0;
    end
  end

  assign pwm_out   = (period_q != 0) && (counter < duty_q);
  assign pwm_n_out = ~pwm_out;
  assign irq       = (period_q != 0) && (counter == period_q - 1'b1);

endmodule
