// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// QSPI slave: standard (1-bit) and quad (4-bit) SPI mode 0, 8-bit frames
// OpenCores spi/quad-spi style: io[0]=MOSI/IO0, io[1]=MISO/IO1, io[3:2]=IO2/3
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module QSPI_top (
  input  logic       clk,
  input  logic       rst_n,
  input  logic       sclk,
  input  logic       csn,
  inout  tri  [3:0]  io,
  input  logic       wen,
  input  logic [3:0] waddr,      // 0: tx_reg, 2: mode (0=std, 1=quad)
  input  logic [7:0] wdata,
  input  logic       ren,
  input  logic [3:0] raddr,      // 0: rx_reg, 1: tx_reg
  output logic [7:0] rdata,
  output logic       irq
);
  logic [7:0] tx_q, rx_q;
  logic [1:0] mode;
  logic       dir;          // 0 = slave drives io (quad read), 1 = release (quad write)
  logic [2:0] bit_cnt;      // std: 0..7
  logic [1:0] qcnt;         // quad nibble counter 0..1
  logic       sclk_d, byte_done;

  // output drive: std drives io[1]; quad drives io[3:0] with tx nibbles
  logic [3:0] io_oe, io_out;
  assign io = io_oe ? io_out : 4'bzzzz;

  wire std_mode = (mode == 2'd0);

  // present first bit while SCLK low (mode 0 timing), update on falling edge
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      io_oe <= 4'b0010; io_out <= 4'b0010;  // std MISO=1 idle
    end else if (csn) begin
      // present first output while CSn high: std -> tx[7] on io[1]; quad -> tx[7:4]
      io_oe       <= std_mode ? 4'b0010 : (dir ? 4'b0000 : 4'b1111);
      io_out[3:2] <= tx_q[7:6];
      io_out[1]   <= std_mode ? tx_q[7] : tx_q[5];
      io_out[0]   <= tx_q[4];
    end else if (sclk_d && !sclk) begin     // SCLK falling: advance output
      if (std_mode) begin
        io_oe  <= 4'b0010;
        io_out[1] <= tx_q[7 - bit_cnt];    // bit_cnt already incremented on sample
      end else if (!dir) begin              // quad read: slave drives tx nibbles
        io_oe  <= 4'b1111;
        io_out <= (qcnt == 2'd0) ? tx_q[7:4] : tx_q[3:0];
      end else begin
        io_oe  <= 4'b0000;                 // quad write: release for master
      end
    end else if (!std_mode) begin
      io_oe <= dir ? 4'b0000 : 4'b1111;    // quad: reflect dir even between edges
    end
  end

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      sclk_d <= 1'b0; bit_cnt <= '0; qcnt <= '0;
      rx_q <= '0; tx_q <= '0; mode <= '0; dir <= 1'b0; byte_done <= 1'b0;
    end else begin
      sclk_d <= sclk;
      byte_done <= 1'b0;
      if (wen && waddr == 4'd0) tx_q <= wdata;
      if (wen && waddr == 4'd2) mode  <= wdata[1:0];
      if (wen && waddr == 4'd3) dir   <= wdata[0];
      if (!csn && sclk && !sclk_d) begin
        if (std_mode) begin
          rx_q <= {rx_q[6:0], io[0]};
          if (bit_cnt == 3'd7) begin
            bit_cnt <= '0; byte_done <= 1'b1;
          end else bit_cnt <= bit_cnt + 1'b1;
        end else begin
          rx_q <= {rx_q[3:0], io[3:0]};      // 4 bits per clock, MSB nibble first
          if (qcnt == 2'd1) begin
            qcnt <= '0; byte_done <= 1'b1;
          end else qcnt <= qcnt + 1'b1;
        end
      end
      if (csn) begin bit_cnt <= '0; qcnt <= '0; end
    end
  end

  assign rdata = (raddr == 4'd0) ? rx_q :
                 (raddr == 4'd1) ? tx_q : 8'h00;
  assign irq   = byte_done;

endmodule
