// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// MIPI RFFE slave: SSC + SA[1:0] + PC + AD[4:0] + DATA[7:0], then bus park
// Write (PC=0): master sends data; Read (PC=1): slave drives data (push-pull).
// OpenCores rffe/pmic style register interface.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module RFFE_top #(
  parameter logic [1:0] RFFE_ADDR = 2'b01
)(
  input  logic       clk,
  input  logic       rst_n,
  inout  tri         sdata,
  input  logic       sclk,
  output logic [7:0] rx_byte,        // {AD, data} register write captured
  output logic [7:0] rx_addr,
  output logic       rx_valid,
  input  logic [7:0] tx_byte,        // data returned for reads
  output logic       busy,
  output logic       irq
);
  logic sclk_s, sclk_d, sdata_s, sdata_d;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      sclk_s <= 1'b0; sclk_d <= 1'b0; sdata_s <= 1'b1; sdata_d <= 1'b1;
    end else begin
      sclk_s <= sclk; sclk_d <= sclk_s;
      sdata_s <= sdata; sdata_d <= sdata_s;
    end
  end
  wire sclk_rise =  sclk_s & ~sclk_d;
  wire sclk_fall = ~sclk_s &  sclk_d;
  wire ssc_det   = ~sdata_s &  sdata_d & sclk_s;   // SSC: sdata falls while sclk high

  typedef enum logic [1:0] {ST_IDLE, ST_HEAD, ST_DATA, ST_PARK} st_t;
  st_t      state;
  logic [3:0] bit_cnt;     // HEAD: 0..2 (SA+PC), then AD folds into HEAD 3..7
  logic [7:0] shift;
  logic       rw;
  logic       sd_oe, sd_out;

  assign sdata   = sd_oe ? sd_out : 1'bz;
  assign busy    = (state != ST_IDLE);
  assign irq     = rx_valid;
  assign rx_addr = {3'b000, shift_hold};

  logic [4:0] shift_hold;  // captured register address

  wire [7:0] head_w = {shift[6:0], sdata_s};

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= ST_IDLE; bit_cnt <= '0; shift <= '0; shift_hold <= '0;
      rw <= 1'b0; sd_oe <= 1'b0; sd_out <= 1'b1; rx_valid <= 1'b0;
    end else begin
      rx_valid <= 1'b0;
      if (ssc_det) begin
        state <= ST_HEAD; bit_cnt <= '0; sd_oe <= 1'b0;
      end else case (state)
        ST_HEAD: if (sclk_rise) begin
          shift <= head_w;
          if (bit_cnt == 4'd7) begin
            // head_w = {SA[1:0], PC, AD[4:0]}
            if (head_w[7:6] == RFFE_ADDR) begin
              rw <= head_w[5];
              shift_hold <= head_w[4:0];
              bit_cnt <= '0;
              state <= ST_DATA;
            end else state <= ST_IDLE;
          end else bit_cnt <= bit_cnt + 1'b1;
        end
        ST_DATA: begin
          if (!rw && sclk_rise) begin          // write: sample master's data
            shift <= head_w;
            if (bit_cnt == 4'd7) begin
              rx_byte <= head_w;
              bit_cnt <= '0; state <= ST_PARK; rx_valid <= 1'b1;
            end else bit_cnt <= bit_cnt + 1'b1;
          end else if (rw && sclk_fall) begin  // read: drive next data bit
            sd_oe <= 1'b1;
            sd_out <= tx_byte[7-bit_cnt];
            if (bit_cnt == 4'd7) begin
              bit_cnt <= '0; sd_oe <= 1'b0; state <= ST_PARK;
            end else bit_cnt <= bit_cnt + 1'b1;
          end
        end
        ST_PARK: if (sclk_fall) begin
          sd_oe <= 1'b0; state <= ST_IDLE;     // bus park then idle
        end
        default: state <= ST_IDLE;
      endcase
    end
  end

endmodule
