// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// RGMII PHY-side datapath: 4-bit DDR TX (nibble per clock edge) + RX capture
// TX: bytes from host FIFO -> nibbles on txd/tx_ctl (DDR on tx_clk)
// RX: nibbles on rxd/rx_ctl (DDR on rx_clk) -> reassembled into FIFO
// Loopback-compatible (rx=tx). OpenCores ethernet/rgmii style.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module RGMII_top #(
  parameter int DEPTH = 16
)(
  input  logic       clk,
  input  logic       rst_n,
  input  logic       tx_clk,
  output logic [3:0] txd,
  output logic       tx_ctl,
  input  logic       rx_clk,
  input  logic [3:0] rxd,
  input  logic       rx_ctl,
  input  logic       wen,
  input  logic [3:0] waddr,
  input  logic [7:0] wdata,
  input  logic       ren,
  input  logic [3:0] raddr,
  output logic [7:0] rdata,
  output logic [4:0] count,
  output logic       irq
);
  // TX queue (bytes to send)
  logic [7:0]  txq [0:7];
  logic [2:0]  tx_wr, tx_rd;
  logic [3:0]  txd_hi, txd_lo; // nibble for high/low phase of tx_clk
  logic        tx_ctl_q;

  // push on host write (waddr 0 = data)
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin tx_wr <= '0; end
    else if (wen && waddr == 4'd0) begin
      txq[tx_wr] <= wdata;
      tx_wr <= tx_wr + 1'b1;
    end
  end

  // TX DDR output (yosys-synthesizable): a single posedge-tx_clk process loads
  // both nibbles of the next byte; a combinational mux on the tx_clk level
  // selects which nibble drives txd (hi while tx_clk=1, lo while tx_clk=0),
  // so txd still changes on every tx_clk edge exactly as a DDR output would.
  // On real silicon this mux would be mapped to an ODDR/ALTDDIO primitive.
  always_ff @(posedge tx_clk or negedge rst_n) begin
    if (!rst_n) begin
      txd_hi <= 4'h0; txd_lo <= 4'h0; tx_ctl_q <= 1'b0; tx_rd <= '0;
    end else if (tx_wr != tx_rd) begin
      tx_ctl_q <= 1'b1;
      txd_hi   <= txq[tx_rd][7:4];
      txd_lo   <= txq[tx_rd][3:0];
      tx_rd    <= tx_rd + 1'b1;
    end else begin
      tx_ctl_q <= 1'b0;
    end
  end
  assign txd    = tx_clk ? txd_hi : txd_lo;
  assign tx_ctl = tx_ctl_q;

  // RX DDR capture
  logic [7:0]  rxq [0:DEPTH-1];
  logic [4:0]  rx_wr;
  logic [3:0]  rx_hi;
  logic        rx_half;
  logic        rxv_s, rxv_d, rxc_s, rxc_d;
  logic [3:0]  rxd_s, rxd_d;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rxv_s <= 1'b0; rxv_d <= 1'b0; rxc_s <= 1'b0; rxc_d <= 1'b0;
      rxd_s <= '0; rxd_d <= '0;
    end else begin
      rxv_s <= rx_clk; rxv_d <= rxv_s;
      rxc_s <= rx_ctl; rxc_d <= rxc_s;
      rxd_s <= rxd;    rxd_d <= rxd_s;
    end
  end
  wire rxv_edge = rxv_s ^ rxv_d;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rx_wr <= '0; rx_half <= 1'b0; rx_hi <= '0;
    end else if (rxv_edge) begin
      if (rxc_d) begin
        if (!rx_half) begin
          rx_hi   <= rxd_d;
          rx_half <= 1'b1;
        end else begin
          rxq[rx_wr[3:0]] <= {rx_hi, rxd_d};
          rx_wr   <= rx_wr + 1'b1;
          rx_half <= 1'b0;
        end
      end else begin
        rx_half <= 1'b0;
      end
    end
  end

  assign count = rx_wr;
  assign rdata = rxq[raddr[3:0]];
  assign irq   = (rx_wr != 0) && ren;

endmodule
