// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// SPI slave, mode 0 (CPOL=0 CPHA=0), 8-bit frames, byte IRQ
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module SPI_top (
  input  logic       clk,
  input  logic       rst_n,
  input  logic       sclk,
  input  logic       mosi,
  output logic       miso,
  input  logic       csn,
  input  logic       wen,
  input  logic [3:0] waddr,
  input  logic [7:0] wdata,
  input  logic       ren,
  input  logic [3:0] raddr,
  output logic [7:0] rdata,
  output logic       irq
);
  logic [7:0] tx_q, rx_q;
  logic [2:0] bit_cnt;
  logic       sclk_d, byte_done;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      sclk_d <= 1'b0; bit_cnt <= '0; rx_q <= '0;
      tx_q <= '0; byte_done <= 1'b0;
    end else begin
      sclk_d <= sclk;
      byte_done <= 1'b0;
      if (wen && waddr == 4'd0) tx_q <= wdata;
      if (!csn && sclk && !sclk_d) begin
        rx_q <= {rx_q[6:0], mosi};
        if (bit_cnt == 3'd7) begin
          bit_cnt <= '0;
          byte_done <= 1'b1;
        end else begin
          bit_cnt <= bit_cnt + 1'b1;
        end
      end
      if (csn) bit_cnt <= '0;
    end
  end

  assign miso  = tx_q[7 - bit_cnt];
  assign rdata = (raddr == 4'd0) ? rx_q :
                 (raddr == 4'd1) ? tx_q : 8'h00;
  assign irq   = byte_done;

endmodule
