// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// MIPI SPMI slave: SSC + SA[3:0] + CMD[3:0] + AD[7:0] + DATA[7:0]
// Simplified command set: CMD 0x0 = register write, 0x1 = register read.
// Two-wire open-drain style, OpenCores spmi/pmic bus pattern.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module SPMI_top #(
  parameter logic [3:0] SPMI_ADDR = 4'h5
)(
  input  logic       clk,
  input  logic       rst_n,
  inout  tri         sdata,
  input  logic       sclk,
  output logic [7:0] rx_byte,
  output logic [7:0] rx_addr,
  output logic       rx_valid,
  input  logic [7:0] tx_byte,
  output logic       busy,
  output logic       irq
);
  logic sclk_s, sclk_d, sdata_s, sdata_d;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      sclk_s <= 1'b0; sclk_d <= 1'b0; sdata_s <= 1'b1; sdata_d <= 1'b1;
    end else begin
      sclk_s <= sclk; sclk_d <= sclk_s;
      sdata_s <= sdata; sdata_d <= sdata_s;
    end
  end
  wire sclk_rise =  sclk_s & ~sclk_d;
  wire sclk_fall = ~sclk_s &  sclk_d;
  wire ssc_det   = ~sdata_s &  sdata_d & sclk_s;

  typedef enum logic [2:0] {ST_IDLE, ST_HEAD, ST_ADDR, ST_DATA, ST_ACKP, ST_IGNORE} st_t;
  st_t      state;
  logic [3:0] bit_cnt;
  logic [7:0] shift, addr_q;
  logic [3:0] cmd;
  logic       sd_oe;

  assign sdata   = drive_low_c ? 1'b0 : 1'bz;   // open-drain: ACK + read data
  assign busy    = (state != ST_IDLE) && (state != ST_IGNORE);
  assign irq     = rx_valid;
  assign rx_addr = addr_q;

  wire [7:0] head_w = {shift[6:0], sdata_s};

  // read data: registered on SCLK fall (the post-address fall presents bit 7)
  wire drive_low_c = sd_oe;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      state <= ST_IDLE; bit_cnt <= '0; shift <= '0; addr_q <= '0; cmd <= '0;
      sd_oe <= 1'b0; rx_byte <= '0; rx_valid <= 1'b0;
    end else begin
      rx_valid <= 1'b0;
      if (ssc_det) begin
        state <= ST_HEAD; bit_cnt <= '0; sd_oe <= 1'b0;
      end else case (state)
        ST_HEAD: if (sclk_rise) begin
          shift <= head_w;
          if (bit_cnt == 4'd7) begin
            if (head_w[7:4] == SPMI_ADDR) begin
              cmd <= head_w[3:0];
              bit_cnt <= '0; state <= ST_ADDR;
            end else state <= ST_IGNORE;
          end else bit_cnt <= bit_cnt + 1'b1;
        end
        ST_ADDR: if (sclk_rise) begin
          shift <= head_w;
          if (bit_cnt == 4'd7) begin
            addr_q <= head_w; bit_cnt <= '0;
            sd_oe  <= 1'b0;
            state <= (cmd == 4'h0) ? ST_DATA :   // write: data follows
                     (cmd == 4'h1) ? ST_ACKP : ST_IGNORE;
          end else bit_cnt <= bit_cnt + 1'b1;
        end
        // write: receive 8 data bits, then ACK (drive 0 one bit)
        ST_DATA: if (sclk_rise) begin
          shift <= head_w;
          if (bit_cnt == 4'd7) begin
            rx_byte <= head_w; rx_valid <= 1'b1;
            bit_cnt <= '0; state <= ST_ACKP;
          end else bit_cnt <= bit_cnt + 1'b1;
        end
        // ACK pulse (write) or read data phase (cmd==1)
        ST_ACKP: begin
          if (cmd == 4'h0) begin                 // write ACK: drive low 1 bit
            if (sclk_fall) sd_oe <= 1'b1;
            else if (sclk_rise) begin sd_oe <= 1'b0; state <= ST_IDLE; end
          end else if (cmd == 4'h1) begin        // read data: drive on fall
            if (sclk_fall) begin
              sd_oe <= (tx_byte[7-bit_cnt] == 1'b0);
              if (bit_cnt == 4'd7) begin
                bit_cnt <= '0; state <= ST_IDLE;
              end else bit_cnt <= bit_cnt + 1'b1;
            end
          end else state <= ST_IDLE;
        end
        default: ;
      endcase
    end
  end

endmodule
