// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// UEC simplified: framed echo.
// Frame: START(1b 0) + STP + LEN + HDR[8] + payload(LEN-8) + CRC32 + END.
// Raw NRZ both ways; length-based framing; STP=0xFB, END=0xFD.
// Differential pair modeled single-ended. LCRC = zlib CRC32.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module UEC_top #(
  parameter int BAUD_DIV = 20,
  parameter int MAXB     = 8
)(
  input  logic        clk,
  input  logic        rst_n,
  input  logic        refclk,
  input  logic        rx,
  output logic        tx,
  output logic        busy,
  output logic        irq
);
  localparam logic [7:0] STP = 8'hFB, END_B = 8'hFD;
  localparam int HB = 8;

  function automatic logic [31:0] crc32_u(input logic [31:0] c, input logic b);
    logic fb;
    begin fb = c[0]^b; crc32_u = c>>1; if (fb) crc32_u = crc32_u ^ 32'hEDB88320; end
  endfunction

  logic [15:0] tmr; logic phase;
  wire tick = (tmr == BAUD_DIV-1);
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin tmr <= '0; phase <= 1'b0; end
    else if (tick) begin tmr <= '0; phase <= ~phase; end
    else tmr <= tmr + 1'b1;
  end

  // ---------------- TX (CAN-style field serializer) ----------------
  typedef enum logic [1:0] {T_IDLE, T_PKT, T_END} t_t;
  t_t          tstate;
  logic [7:0]  tx_shift;
  logic [31:0] tx_crc, crc_snap;
  logic [5:0]  tbit;
  logic [3:0]  tcur;
  logic [5:0]  tlen;
  logic [2:0]  tfld;           // 0=STP 1=LEN 2=HDR 3=DATA 4=CRC 5=END
  logic [7:0]  tx_mem [0:15];
  logic        tx_go, oe_q, out_q;
  logic [3:0]  ta_cnt; logic ta_arm;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      tstate <= T_IDLE; tbit <= '0; tfld <= '0; tlen <= '0; tcur <= '0;
      tx_crc <= '0; crc_snap <= '0; tx_shift <= '0; tx_go <= 1'b0;
      oe_q <= 1'b0; out_q <= 1'b1; ta_cnt <= '0; ta_arm <= 1'b0;
    end else begin
      if (ta_cnt != 0 && tick) ta_cnt <= ta_cnt - 1'b1;
      if (ta_cnt == 0 && ta_arm) begin tx_go <= 1'b1; ta_arm <= 1'b0; end
      if (tick && !phase) begin
        case (tstate)
          T_IDLE: if (tx_go) begin
            tx_go <= 1'b0; oe_q <= 1'b1; out_q <= 1'b0;
            tbit <= '0; tfld <= '0;
            tstate <= T_PKT;
          end
          T_PKT: begin
            oe_q <= 1'b1;
            if (tfld == 3'd4) begin
              out_q    <= ~crc_snap[0];
              crc_snap <= crc_snap >> 1;
            end else begin
              out_q <= tx_shift[0];
              if (tfld == 3'd2 || tfld == 3'd3)
                tx_crc <= crc32_u(tx_crc, tx_shift[0]);
              tx_shift <= tx_shift >> 1;
            end
            if (tfld == 3'd4) begin
              if (tbit == 6'd31) begin tfld <= 3'd5; tbit <= '0; tx_shift <= END_B; end
              else tbit <= tbit + 1'b1;
            end else if (tbit == 6'd7) begin
              tbit <= '0;
              case (tfld)
                3'd0: begin tx_shift <= {2'b0, tlen}; tfld <= 3'd1; end
                3'd1: begin tx_shift <= tx_mem[0]; tfld <= 3'd2;
                            tx_crc <= 32'hFFFFFFFF; tcur <= '0; end
                3'd2: begin
                  if (tcur == 4'd7) begin tx_shift <= tx_mem[8]; tfld <= 3'd3; tcur <= 4'd8; end
                  else begin tcur <= tcur + 4'd1; tx_shift <= tx_mem[tcur + 4'd1]; end
                end
                3'd3: begin
                  if (tcur == (tlen[3:0] - 4'd1)) begin
                    tfld <= 3'd4;
                    crc_snap <= crc32_u(tx_crc, tx_shift[0]);
                  end
                  else begin tcur <= tcur + 4'd1; tx_shift <= tx_mem[tcur + 4'd1]; end
                end
                3'd5: tstate <= T_END;
                default: ;
              endcase
            end else tbit <= tbit + 1'b1;
          end
          T_END: begin oe_q <= 1'b0; out_q <= 1'b1; tstate <= T_IDLE; end
          default: tstate <= T_IDLE;
        endcase
      end
    end
  end

  assign tx   = oe_q ? out_q : 1'bz;
  assign busy = (rstate != R_IDLE) || (tstate != T_IDLE);

  // ---------------- RX (length-based framing, start-bit resync) ----------------
  typedef enum logic [1:0] {R_IDLE, R_BYTE} r_t;
  r_t          rstate;
  logic        rxs, rxs_d;
  logic        rtmr_en, rphase;
  logic [15:0] rtmr;
  logic [2:0]  rbitc;
  logic [7:0]  rsh;
  logic [5:0]  ridx;
  logic [5:0]  len_q;
  logic [7:0]  buf_mem [0:HB+MAXB+7];
  logic        rx_err, rx_done;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin rxs <= 1'b1; rxs_d <= 1'b1; end
    else begin rxs <= rx; rxs_d <= rxs; end
  end
  wire start_edge = rxs_d & ~rxs;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin rtmr_en <= 1'b0; rtmr <= '0; rphase <= 1'b0; end
    else begin
      if (rstate == R_IDLE && start_edge && tstate == T_IDLE) begin
        rtmr_en <= 1'b1; rtmr <= BAUD_DIV/2; rphase <= 1'b1;   // first sample = START bit (discarded)
      end else if (rtmr_en && (rtmr == BAUD_DIV-1)) begin
        rtmr <= '0; rphase <= ~rphase;
      end else if (rtmr_en) rtmr <= rtmr + 1'b1;
    end
  end
  wire rsample = rtmr_en && (rtmr == BAUD_DIV-1) && rphase;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rstate <= R_IDLE; rbitc <= '0; rsh <= '0; ridx <= '0; len_q <= '0;
      rx_err <= 1'b0; rx_done <= 1'b0; buf_mem[0] <= '0;
    end else begin
      rx_done <= 1'b0;
      if (rsample) begin
        case (rstate)
          R_IDLE: begin
            // this sample is the START bit: discard, begin STP at next sample
            rstate <= R_BYTE; rbitc <= '0; ridx <= '0; rsh <= '0;
          end
          R_BYTE: begin
            rsh <= {rxs, rsh[7:1]};
            if (rbitc == 3'd7) begin
              logic [7:0] nb; nb = {rxs, rsh[7:1]};
              if (ridx == 0) begin
                if (nb !== STP) rx_err <= 1'b1;
                ridx <= 1;
              end else if (ridx == 1) begin
                buf_mem[1] <= nb; len_q <= nb[5:0]; ridx <= 2;
              end else if (ridx == (6'd2 + len_q + 6'd4)) begin
                if (nb !== END_B) rx_err <= 1'b1;
                else begin
                  logic [31:0] c; c = 32'hFFFFFFFF;
                  for (int i = 2; i < HB + MAXB + 8; i++) begin
                    if (i <= 6'd1 + len_q)
                      for (int j = 0; j < 8; j++)
                        c = crc32_u(c, buf_mem[i][j]);
                  end
                  c = c ^ 32'hFFFFFFFF;
                  if ({buf_mem[6'd5+len_q], buf_mem[6'd4+len_q],
                       buf_mem[6'd3+len_q], buf_mem[6'd2+len_q]} !== c)
                    rx_err <= 1'b1;
                  else rx_done <= 1'b1;
                end
                rstate <= R_IDLE; ridx <= '0; rtmr_en <= 1'b0;
              end else begin
                buf_mem[ridx[5:0]] <= nb;
                ridx <= ridx + 6'd1;
              end
              rbitc <= '0;
            end else rbitc <= rbitc + 3'd1;
          end
          default: rstate <= R_IDLE;
        endcase
      end
    end
  end

  // echo: retransmit received content (HDR+payload identical frame)
  always_ff @(posedge clk) begin
    if (rx_done) begin
      tlen <= len_q;
      for (int i = 2; i < HB + MAXB + 6; i++)
        tx_mem[i-2] <= buf_mem[i];
      ta_cnt <= 4'd6; ta_arm <= 1'b1;
    end
  end

  assign irq = rx_done;

endmodule
