// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// USB 2.0 full-speed device controller, echo mode (FS, addr 0 / ep 0 subset)
// RX: K-edge resync, NRZI decode, SYNC, de-stuffing, PID check, CRC16, EOP
// TX: CAN-style serializer; NRZI; bit stuffing; SYNC/PID/payload/CRC16; SE0 EOP
// Turn-around delay + self-transmit RX gating for pin-shared echo.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module USB2_0_top #(
  parameter int BAUD_DIV = 20,        // clk per half-bit (bit = 2*BAUD_DIV)
  parameter int MAXB     = 8          // max payload bytes
)(
  input  logic        clk,
  input  logic        rst_n,
  inout  tri          dp,
  inout  tri          dm,
  output logic        busy,
  output logic        irq
);
  // ---------------- bit timer (2 phases per bit) ----------------
  logic [15:0] tmr;
  logic        phase;
  wire         tick = (tmr == BAUD_DIV-1);
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin tmr <= '0; phase <= 1'b0; end
    else if (tick) begin tmr <= '0; phase <= ~phase; end
    else tmr <= tmr + 1'b1;
  end

  // ---------------- line sampling ----------------
  logic dps, dms;
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin dps <= 1'b1; dms <= 1'b0; end
    else begin dps <= dp; dms <= dm; end
  end
  wire line_j   =  dps & ~dms;
  wire line_k   = ~dps &  dms;
  wire line_se0 = ~dps & ~dms;

  function automatic logic [15:0] crc16_u(input logic [15:0] c, input logic b);
    logic fb;
    begin
      fb = c[0] ^ b;
      crc16_u = c >> 1;
      if (fb) crc16_u = crc16_u ^ 16'h8005;
    end
  endfunction

  // ---------------- TX ----------------
  typedef enum logic [1:0] {T_IDLE, T_PKT, T_EOP0, T_EOPJ} tx_t;
  tx_t         tstate;
  logic [7:0]  tx_shift;
  logic [15:0] tx_crc;
  logic [5:0]  tbit;
  logic [2:0]  tbyte;
  logic [1:0]  tfld;          // 0=SYNC 1=PID 2=DATA 3=CRC
  logic [3:0]  run_cnt;
  logic [7:0]  tx_mem [0:MAXB-1];
  logic [3:0]  tx_pid;
  logic [4:0]  tx_len;
  logic        tx_go;
  logic        oe_q, dp_q, dm_q;

  wire [7:0] sync_b = 8'h80;
  wire [7:0] pid_b  = {~tx_pid, tx_pid};

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      tstate <= T_IDLE; tfld <= '0; tbit <= '0; tbyte <= '0;
      run_cnt <= '0; oe_q <= 1'b0; dp_q <= 1'b1; dm_q <= 1'b0;
      tx_crc <= '0; tx_shift <= '0; tx_go <= 1'b0; tx_len <= '0; tx_pid <= '0;
      for (int i = 0; i < MAXB; i++) tx_mem[i] <= '0;
    end else begin
      if (tick && !phase) begin                 // drive point
        case (tstate)
          T_IDLE: if (tx_go) begin
            tx_go   <= 1'b0;
            tfld    <= 2'd0; tbit <= '0;
            run_cnt <= '0;
            tx_crc  <= '0;
            tx_shift<= sync_b >> 1;             // bit0 pre-driven below
            oe_q    <= 1'b1;
            dp_q    <= 1'b0; dm_q <= 1'b1;      // SYNC bit0 = K
            tstate  <= T_PKT;
          end
          T_PKT: begin
            if (run_cnt == 4'd6 && tfld != 2'd0) begin
              dp_q <= ~dp_q; dm_q <= ~dm_q;     // stuff bit = 0 -> toggle
              run_cnt <= 4'd1;
            end else begin
              if (tfld == 2'd3) begin           // CRC: send ~tx_crc[0]
                if (tx_crc[0] == 1'b1) begin dp_q <= ~dp_q; dm_q <= ~dm_q; end
                run_cnt <= (~tx_crc[0]) ? run_cnt + 1'b1 : 4'd1;
                tx_crc  <= tx_crc >> 1;
              end else begin
                if (tx_shift[0] == 1'b0) begin dp_q <= ~dp_q; dm_q <= ~dm_q; end
                if (tfld == 2'd2) tx_crc <= crc16_u(tx_crc, tx_shift[0]);
                run_cnt <= tx_shift[0] ? run_cnt + 1'b1 : 4'd1;
                tx_shift <= tx_shift >> 1;
              end
              if (tfld == 2'd0) begin
                if (tbit == 6'd6) begin tfld <= 2'd1; tx_shift <= pid_b; tbit <= '0; end
                else tbit <= tbit + 1'b1;
              end else if (tfld == 2'd1) begin
                if (tbit == 6'd7) begin
                  tbit <= '0;
                  if (tx_len == 5'd0) tfld <= 2'd3;
                  else begin tfld <= 2'd2; tbyte <= '0; tx_shift <= tx_mem[0]; end
                end else tbit <= tbit + 1'b1;
              end else if (tfld == 2'd2) begin
                if (tbit == 6'd7) begin
                  tbit <= '0;
                  if (tbyte == tx_len[2:0] - 3'd1) tfld <= 2'd3;
                  else begin tbyte <= tbyte + 3'd1; tx_shift <= tx_mem[tbyte + 3'd1]; end
                end else tbit <= tbit + 1'b1;
              end else begin
                if (tbit == 6'd15) tstate <= T_EOP0;
                else tbit <= tbit + 1'b1;
              end
            end
          end
          T_EOP0: begin
            oe_q <= 1'b1; dp_q <= 1'b0; dm_q <= 1'b0;   // SE0
            tstate <= T_EOPJ;
          end
          T_EOPJ: begin
            oe_q <= 1'b0;                               // release to J
            tstate <= T_IDLE;
          end
          default: tstate <= T_IDLE;
        endcase
      end
    end
  end

  assign dp = oe_q ? dp_q : 1'bz;
  assign dm = oe_q ? dm_q : 1'bz;

  // ---------------- RX ----------------
  typedef enum logic [1:0] {R_IDLE, R_SYNC, R_PKT} rx_t;
  rx_t         rstate;
  logic [2:0]  rbit;
  logic [7:0]  rshift;
  logic [5:0]  ridx;
  logic [3:0]  rrun;
  logic        rdstf;
  logic [7:0]  buf_mem [0:19];
  logic        rprev_j;
  logic        rx_err, rx_done;
  logic        k_now, k_d;
  logic [15:0] rtmr;
  logic        rphase;
  logic [3:0]  ta_cnt;
  logic        ta_arm;
  wire         rtick  = (rtmr == BAUD_DIV-1);
  wire         k_rise = k_now & ~k_d;
  wire         rx_sample_bit = (line_j == rprev_j);

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rtmr <= '0; rphase <= 1'b0; k_now <= 1'b0; k_d <= 1'b0;
      ta_cnt <= '0; ta_arm <= 1'b0;
    end else begin
      k_now <= line_k; k_d <= k_now;
      if (ta_cnt != 0 && tick) ta_cnt <= ta_cnt - 1'b1;
      if (ta_cnt == 0 && ta_arm) begin tx_go <= 1'b1; ta_arm <= 1'b0; end
      if (rstate == R_IDLE && k_rise && tstate == T_IDLE) begin
        rtmr   <= BAUD_DIV/2;               // first sample half bit after K edge
        rphase <= 1'b1;
      end else if (rtick) begin
        rtmr <= '0;
        rphase <= ~rphase;
      end else rtmr <= rtmr + 1'b1;
    end
  end

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      rstate <= R_IDLE; rbit <= '0; rshift <= '0; ridx <= '0;
      rrun <= '0; rdstf <= 1'b0; rprev_j <= 1'b1;
      rx_err <= 1'b0; rx_done <= 1'b0; buf_mem[0] <= '0;
      tx_len <= '0; tx_pid <= '0;
    end else begin
      rx_done <= 1'b0;

      if (rtick && rphase) begin
        case (rstate)
          R_IDLE: if (line_k && tstate == T_IDLE) begin
            // this sample IS sync bit 0 (K); consume it, count from 1
            rstate <= R_SYNC; rbit <= 3'd1; rprev_j <= 1'b0;
            rrun <= '0; rdstf <= 1'b0; ridx <= '0;
          end
          R_SYNC: begin
            rprev_j <= line_j;
            if (rbit == 3'd7) begin
              rstate <= R_PKT; rbit <= '0; rshift <= '0; ridx <= '0;
              rdstf <= 1'b1; rrun <= '0;
            end else rbit <= rbit + 1'b1;
          end
          R_PKT: begin
            if (line_se0) begin
              rstate <= R_IDLE;
              if (ridx >= 6'd3) begin
                logic [3:0] p; p = buf_mem[0][3:0];
                if (buf_mem[0][7:4] !== ~p) rx_err <= 1'b1;
                else begin
                  logic [15:0] c; c = 16'hFFFF;
                  for (int i = 1; i < 20; i++) begin
                    if (i <= ridx-3)
                      for (int j = 0; j < 8; j++)
                        c = crc16_u(c, buf_mem[i][j]);
                  end
                  // first received CRC byte is the LOW byte
                  if ({buf_mem[ridx-1], buf_mem[ridx-2]} !== ~c) rx_err <= 1'b1;
                  else begin
                    tx_len  <= (ridx - 6'd3);
                    tx_pid  <= p;
                    for (int i = 1; i < 20; i++)
                      if (i <= ridx-3) tx_mem[i-1] <= buf_mem[i];
                    rx_done <= 1'b1;
                    ta_cnt  <= 4'd6;            // turn-around: 6 bit times
                    ta_arm  <= 1'b1;
                  end
                end
              end else rx_err <= 1'b1;
            end else begin
              rprev_j <= line_j;
              if (rdstf && rrun == 4'd6) begin
                if (rx_sample_bit !== 1'b0) rx_err <= 1'b1;
                rrun <= 4'd1;                   // stuff bit counts as 1 (breaks run)
              end else begin
                rshift <= {rx_sample_bit, rshift[7:1]};
                if (rx_sample_bit) rrun <= rrun + 1'b1;
                else rrun <= 4'd1;
                if (rbit == 3'd7) begin
                  buf_mem[ridx[5:0]] <= {rx_sample_bit, rshift[7:1]};
                  ridx <= ridx + 6'd1;
                  rbit <= '0;
                end else rbit <= rbit + 1'b1;
              end
            end
          end
          default: rstate <= R_IDLE;
        endcase
      end
    end
  end

  assign busy = (rstate != R_IDLE) || (tstate != T_IDLE);
  assign irq  = rx_done;

endmodule
