// SPDX-License-Identifier: Apache-2.0
// ============================================================================
// XGMII MAC datapath: 32-bit SDR TX + RX with term/error column (txc/rxc)
// TX: bytes from host FIFO -> txd on tx_clk with txc column markers
// RX: rxd/rxc on rx_clk -> FIFO; rxc != 0 marks control/Delim
// Loopback-compatible. OpenCores ethernet/xgmii style.
// Auto-generated by gen_framework.py -- Apache-2.0
// ============================================================================
module XGMII_top #(
  parameter int DEPTH = 16
)(
  input  logic        clk,
  input  logic        rst_n,
  input  logic        tx_clk,
  output logic [31:0] txd,
  output logic [3:0]  txc,
  input  logic        rx_clk,
  input  logic [31:0] rxd,
  input  logic [3:0]  rxc,
  input  logic        wen,
  input  logic [3:0]  waddr,     // 0: data
  input  logic [7:0]  wdata,
  input  logic        ren,
  input  logic [3:0]  raddr,
  output logic [7:0]  rdata,
  output logic [4:0]  count,
  output logic        irq
);
  logic [7:0] txq [0:7];
  logic [2:0] tx_wr, tx_rd;
  logic       txen_q;
  logic [1:0] lane;              // 32-bit word = 4 host bytes

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin tx_wr <= '0; tx_rd <= '0; lane <= '0; end
    else if (wen && waddr == 4'd0) begin
      txq[tx_wr] <= wdata;
      tx_wr <= tx_wr + 1'b1;
    end
  end

  always @(posedge tx_clk) begin
    if (!rst_n) begin
      txd <= 32'h0; txc <= 4'hF; txen_q <= 1'b0; tx_rd <= '0; lane <= '0;
    end else if (tx_wr - tx_rd >= 3'd4) begin
      // assemble 4 bytes into one 32-bit word (little-lane order: byte0 -> [7:0])
      txd <= {txq[tx_rd+3'd3], txq[tx_rd+3'd2], txq[tx_rd+3'd1], txq[tx_rd]};
      txc <= 4'h0;                     // all data lanes
      txen_q <= 1'b1;
      tx_rd <= tx_rd + 3'd4;
    end else begin
      txc <= 4'hF;                     // idle: all control lanes -> RX ignores
      txen_q <= 1'b0;
    end
  end

  logic [7:0] rxq [0:DEPTH-1];
  logic [4:0] rx_wr;
  logic       rxclk_s, rxclk_d;

  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin rxclk_s <= 1'b0; rxclk_d <= 1'b0; end
    else begin rxclk_s <= rx_clk; rxclk_d <= rxclk_s; end
  end
  wire rxv_rise = rxclk_s & ~rxclk_d;

  // capture each data lane per rx_clk (ignore control lanes rxc!=0).
  // Lane i writes at rx_wr+i (constant offsets; all NBAs read old rx_wr),
  // then rx_wr advances by the number of data lanes.
  always_ff @(posedge clk or negedge rst_n) begin
    if (!rst_n) rx_wr <= '0;
    else if (rxv_rise && rxc == 4'h0) begin
      if (!rxc[0]) rxq[rx_wr[3:0]]        <= rxd[7:0];
      if (!rxc[1]) rxq[rx_wr[3:0] + 4'd1] <= rxd[15:8];
      if (!rxc[2]) rxq[rx_wr[3:0] + 4'd2] <= rxd[23:16];
      if (!rxc[3]) rxq[rx_wr[3:0] + 4'd3] <= rxd[31:24];
      casez (rxc)
        4'b0000: rx_wr <= rx_wr + 5'd4;
        4'b0001: rx_wr <= rx_wr + 5'd3;
        4'b0010: rx_wr <= rx_wr + 5'd3;
        4'b0100: rx_wr <= rx_wr + 5'd3;
        4'b1000: rx_wr <= rx_wr + 5'd3;
        4'b0101: rx_wr <= rx_wr + 5'd2;
        4'b0110: rx_wr <= rx_wr + 5'd2;
        4'b1001: rx_wr <= rx_wr + 5'd2;
        4'b1010: rx_wr <= rx_wr + 5'd2;
        4'b1100: rx_wr <= rx_wr + 5'd2;
        default: rx_wr <= rx_wr + 5'd1;
      endcase
    end
  end

  assign count = rx_wr;
  assign rdata = rxq[raddr[3:0]];
  assign irq   = (rx_wr != 0) && ren;

endmodule
