# SPDX-License-Identifier: Apache-2.0
# HDCP 2.3 Content Protection Open IP -- sim & synthesis entry points
S      := HDCP_2_3_Content_Protection
DEPS   := 
SIM    ?= iverilog
VFLAGS := -g2012 -Wall
SYN    ?= yosys

all: sim syn

sim:
	$(SIM) $(VFLAGS) -o simv rtl/$(S)_top.sv $(DEPS) tb/$(S)_tb.sv
	./simv

syn:
	cd work && $(SYN) ../syn/$(S)_yosys.ys

clean:
	rm -f simv *.vcd work/*.json work/*_netlist.v
.PHONY: all sim syn clean
